### ISSUE TITLE
manual_run is not working with Sequence

### ISSUE THREAD

**Issue by Olum-hack** [rgc99/irrigation_unlimited#102]
## Version of the custom_component

Home Assistant: 2023.3.3
Irrigation Unlimited: 2023.2.1
Irrigation Unlimited Card: 2022.10.0

## Configuration

Config
```yaml

controllers:
  - name: 'Pumpe'
    preamble: '00:00'
    entity_id: 'switch.garten_bewasserung_wasserpumpe'
    zones:
      - name: "Hecke"
        entity_id: 'switch.garten_bewasserung_hecke'
      - name: "Hochbeet"
        entity_id: 'switch.garten_bewasserung_hochbeet'
      - name: "Rasen"
        entity_id: 'switch.garten_bewasserung_rasen'
      - name: "Vorgarten"
        entity_id: 'switch.garten_bewasserung_vorgarten'
      - name: "Rasen Dusche"
        entity_id: 'switch.garten_bewasserung_rasen_dusche'
    
    sequences:
      - name: "Tropfen"
        delay: '00:00'
        duration: '00:00'
        schedules:
          - name: "Morgen Tropfen"
            time:
              sun: "sunrise"
              before: '01:00'
            anchor: finish
        zones:
          - zone_id: 1
          - zone_id: 2
            
      - name: "Rasen"
        delay: '00:00'
        duration: '00:00'
        schedules:
          - name: "Morgen Rasen"
            time:
              sun: "sunrise"
              before: '01:00'
            anchor: finish
        zones:
          - zone_id: 3
          - zone_id: 4
          - zone_id: 5

```

Lovelace
```yaml
  - title: Manuelle Bewässerung
    type: entities
    entities:
      - entity: input_select.irrigation_unlimited_entities
        name: Controller/Zone
      - entity: input_select.irrigation_unlimited_sequences
        name: Controller/Sequence
      - type: custom:time-picker-card
        entity: input_datetime.irrigation_unlimited_run_time
        hour_mode: 24
        hour_step: 1
        minute_step: 1
        second_step: 5
        name: ''
        layout:
          embedded: true
        link_values: false
        hide:
          seconds: true
      - type: divider
      - type: custom:paper-buttons-row
        buttons:
          - name: Go
            tap_action:
              action: call-service
              service: irrigation_unlimited.shim_manual_run
              service_data:
                time_entity: input_datetime.irrigation_unlimited_run_time
                controller_zone_entity: input_select.irrigation_unlimited_entities
                controller_sequence_entity: input_select.irrigation_unlimited_sequences
          - name: Cancel
            tap_action:
              action: call-service
              service: irrigation_unlimited.shim_cancel
              service_data:
                controller_zone_entity: input_select.irrigation_unlimited_entities
```

## Describe the bug

I can't run the service manual_run or shim_manual_run with a sequence.
It is not working directly as service. It is not working with the Manual run card https://github.com/rgc99/irrigation_unlimited#84-manual-run-card
An it is not working with the Irrigation Unlimited Card.

At fall last year, the manual run card was working.

## Debug log

```text

{"name":"custom_components.pyscript.file.irrigation_unlimited_service_shim.irrigation_unlimited_call_manual_run","message":["Exception in <file.irrigation_unlimited_service_shim.irrigation_unlimited_call_manual_run> line 116:\n time = state.get(time_entity)\n ^\nNameError: invalid name '00:05:00' (should be 'domain.entity' or 'domain.entity.attr')"],"level":"ERROR","source":["custom_components/pyscript/eval.py",480],"timestamp":1679152199.0271795,"exception":"","count":1,"first_occurred":1679152199.0271795}]}

```
