### ISSUE TITLE
ESPHome Sprinkler Controller

### ISSUE THREAD

**Issue by grimmaldus** [rgc99/irrigation_unlimited#103]
Is it possible to integrate this with [ESPHome Sprinkler Controller](https://esphome.io/components/sprinkler) ?

**Comment by rgc99** [comment]
What parts did you want to integrate? Please provide some background on what you would like to achieve.

**Comment by rgc99** [comment]
Stale issue.

**Comment by evercape** [comment]
@grimmaldus you can just run both - use the switches from ESPHome Sprinkler together with the binary sensors from Unlimited.

**Comment by dspasojevic** [comment]
Thanks for building Irrigation Unlimited, it is great new functionality for HA.

The `duration` configuration in the ESPHome Sprinkler controller will override (provide a failsafe for?) the commands from Irrigation Unlimited.

For example, an ESPHome configuration like this:
```
sprinkler:
  - id: irrigation_ctrlr

<snip>
    valves:

<snip>

      - valve_switch: "Vegetable Pods"
        enable_switch: "Enable Vegetable Pods"
        pump_switch_id: main_valve_sw
        run_duration: 180s
        valve_switch_id: irrigation_valve_sw1
```

means that the switch will be disabled after 180s no matter what Irrigation Unlimited plans to do.

There is an alternative way of configuring the valves:

```
      - valve_switch: "Back Garden"
        enable_switch: "Enable Back Garden"
        pump_switch_id: sprinkler_pump_sw1
        run_duration_number:
          id: garden_sprinkler_ctrlr_back_run_duration
          name: "Back Garden Run Duration"
          initial_value: 10
          unit_of_measurement: min
        valve_switch_id: garden_sprinkler_valve_sw1
```

That allows the duration to be set by the caller.

Irrigation Unlimited offers a *lot* of additional value on top of the `sprinkler`. I wonder if it would be possible to delegate shutting off valves to `sprinkler` by adding support for the `run_duration_number`? This is something that I would be interested in contributing if it is aligned with your plans.

**Comment by rgc99** [comment]
The way to do this is by using the actions that the sprinkler controller offers. Use an automation to listen for or monitor the state of one of the binary sensor of Irrigation Unlimited and then issue an action to the sprinkler controller.

For example the automation would trigger when `binary_sensor.irrigation_c1_z1` goes from `off` to `on` and then issue an `sprinkler.start_single_valve` action.

**Comment by dspasojevic** [comment]
This ended up working quite well, albeit with a bit of boilerplate. I created an ESPHome `api` for switching on my different valves:

```
api:
  actions:
...
    - action: start_vege_pods
      variables:
        duration: int
      then:
        - sprinkler.start_single_valve:
            id: irrigation_ctrlr
            valve_number: 1
            run_duration: !lambda 'return duration;'
```

then the automation was relatively simple:

```
alias: Turn Vege Pods On
description: Start a sprinkler valve when irrigation sensor is triggered
triggers:
  - entity_id:
      - binary_sensor.irrigation_unlimited_c1_z2
    trigger: state
    attribute: status
    to: "on"
conditions: []
actions:
  - variables:
      run_duration: >
        {% set time_str = state_attr('binary_sensor.irrigation_unlimited_c1_z2','current_duration') %}
        {% set time_parts = time_str.split(':') %}
        {% set total_seconds = (time_parts[0]|int * 3600) + (time_parts[1]|int * 60) + (time_parts[2]|int) %}
        {{ total_seconds }}
  - action: esphome.esphome_web_f58257_start_vege_pods
    data:
      duration: "{{ run_duration }}"
mode: single
```

there is a corresponding automation for other zones as well as much simpler ones to turn off the valves if the Irrigation Unlimited zones are stopped early.

I am not sure whether `current_duration` or `time_remaining` is better. Given that there is the `off` automation it seems like it would not make much difference.

Thanks for your input @rgc99 - I don't think additional Irrigation Unlimited support is needed for my use cases.
