### ISSUE TITLE
Add skipping days feature

### ISSUE THREAD

**Issue by luixal** [rgc99/irrigation_unlimited#106]
**Is your feature request related to a problem? Please describe.**
From time to time, I just disable irrigation for some days. i.e: this week is rainning almost all days (and I don't own a rain sensor) so I just disable irrigation and next week will enable it again. Thing is, I need to set a remainder so I re-enable it.

**Describe the solution you'd like**
Having a service call like `skip-days` with an integer argument that disables irrigation and re-enables it once that amount of days have past.

**Describe alternatives you've considered**
Right now, I'm using an `input_number` helper (which represents the skip days count) and tow automations:

- One for enabling/disabling irrigation controller if this value changes to 0/above 0
- Another one for decrementing the counter daily

Quite amount of things that could be a good feature to include in this integration.

**Additional context**

**Comment by rgc99** [comment]
This would be a nice feature. More of a pause or temporary disable with a restart date. Don't know what's the best way for the argument; pause for n days or restart on a certain date? Either way it would be internally resolved to an actual date and time. Would need to have the restart time published, probably via an attribute to allow recovery and survive a HA reboot.

**Comment by luixal** [comment]
Yes, I also think it's best to internally use a datetime. I started that way, using two helpers, an `input_number` and an `input_datetime`. In my frontend I just used the first one to input the number of days to skip, an automation was triggered when the `input_number` changed and  it disabled the controller and set the `input_datetime` by adding days to current date. Another automation checked every day and, if the date in the `input_datetime` was previous to current date, it enabled the controller.

Later I removed all that logic and right now I only use the `input_number` and an automation that disables the controller when it changes to a value above 0 and another one that daily decrements the `input_number` and when it reaches 0, enables the controller. I lost the feature of setting it by date.

Anyhow, in my mind this service can be called with tow different arguments, `days` to skip, like this:

```yaml
service: irrigation_unlimited.skip
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
  days: 3
```

or the datetime `until` you want to skip irrigation:

```yaml
service: irrigation_unlimited.skip
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
  until: "2023-06-01 02:00:00"
```

I think the `skip days` or `skip until` it's quite a good, simple and understandable naming for this.

Using a datetime instead of just a date seems useful to me in case I want to pospone irrigation for n days an also skip morning irrigation, for example.

Does this make sense to you?

**Comment by Kolia56** [comment]
It would be a lovely addition indeed

**Comment by rgc99** [comment]
The one of two arguments (days or datetime) approach sounds good. The `days` parameter rather than a number could be made into a time period which would give more flexibility with little work. The syntax would look like:
```yaml
  time: '72:00' # HH:MM
  time: '72:00:00' # HH:MM:SS
  time: 259200 # Seconds
  time: # One or more of the fields below
    days: 3
    hours: 0
    minutes: 0
    seconds: 0
```
It is already used extensively in the integration for fields like `duration` and `delay` for example. Might also be a little more consistent.

**Comment by luixal** [comment]
As you say, it's already used in the integration so parsing/converting code can be reused and it can be a great way to add more flexibilidy easily.

Sounds good to me :)

PS: this feature can be widely incremented, like being able of skipping just one sequence or zone instead of full irrigation only, but I'm on the side of starting slow and iterating if needed.

**Comment by rgc99** [comment]
The changes are in the repository for this feature. It has morphed into a `suspend` service. You can suspend a controller/zone/sequence or sequence zone. Operation is very similar to other service calls like adjust_time but has the following options:

| Service data attribute | Type | Required | Description |
| ---------------------- | ---- | -------- | ----------- |
| `entity_id` | string/list | yes | Controller or zone to suspend. |
| `sequence_id` | number | no | Sequence to suspend. |
| `zones` | number/list | no | Zones to suspend. |
| `for` | duration | see below* | Time to suspend. Supports templating. |
| `until` | string | see below* | A valid datetime string i.e. YYYY-MM-DD HH:MM:SS |
| `reset` | none | see below* | Reset/cancel current suspend. |

\* Must have one and only one of `for`, `until` or `reset`.

```yaml
# Suspend sequence 1 for 2.5 hours
- service: irrigation_unlimited.suspend
  data:
    entity_id: binary_sensor.irrigation_unlimited_c1_m
    sequence_id: 1
    for: "02:30"
```

A few more changes than first anticipated but that is the way things normally roll. Please install from repo and provide some feedback.

Have fun.
