### ISSUE TITLE
Cron example not working? 

### ISSUE THREAD

**Issue by gytisgreitai** [rgc99/irrigation_unlimited#109]
- Installed via HACS
- HASS version: 2023.5.2
- irrigation_unlimited version: 2023.2.1

Config (copy pasted from README):

```
irrigation_unlimited:
  controllers:
    zones:
      - entity_id: "switch.my_switch_1"
    sequences:
      - name: "On the hour from 5am to 5pm"
        duration: "00:05"
        schedules:
          - time:
            cron: "0 5-17 * * *"
        zones:
          - zone_id: 1
```

Error on hass:
```
Invalid config for [irrigation_unlimited]: Invalid time specified: None for dictionary value @ data['irrigation_unlimited']['controllers'][0]['sequences'][0]['schedules'][0]['time']. Got None extra keys not allowed @ data['irrigation_unlimited']['controllers'][0]['sequences'][0]['schedules'][0]['cron']. Got None. (See /home/homeassistant/.homeassistant/configuration.yaml, line 186).
```

**Comment by rgc99** [comment]
The `cron:` line needs to be indented two spaces.
```yaml
irrigation_unlimited:
  controllers:
    zones:
      - entity_id: "switch.my_switch_1"
    sequences:
      - name: "On the hour from 5am to 5pm"
        duration: "00:05"
        schedules:
          - time:
              cron: "0 5-17 * * *"
        zones:
          - zone_id: 1
```
Documentation has been updated. Thanks for reporting this.
