### ISSUE TITLE
zones with adjusted time doesn't work in a sequence

### ISSUE THREAD

**Issue by bulburDE** [rgc99/irrigation_unlimited#111]
I have a sequence with multiple zones. If I adjust the time of the a zone, that zone is ignored. The second zone is executed as planned.

configuration:
```
irrigation_unlimited:
  granularity: 1
  history_span: 30
  controllers:
    all_zones_config:
      show:
        timeline: true   
    zones:
      # I did leave out some irrelevant zones.
      # This is binary_sensor.irrigation_unlimited_c1_z7
      - entity_id: input_boolean.irrigation_test_entity
        zone_id: test
        name: test zone
        maximum: "01:30"     
      # This is binary_sensor.irrigation_unlimited_c1_z8
      - entity_id: input_boolean.irrigation_test_entity_2
        zone_id: test2
        name: test zone2
        maximum: "01:30"         
    sequences:
      - name: Test2
        schedules:
          - time: "01:17"
            weekday: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
            month: ["may", "jun", "jul", "aug"]          
        zones:
          - zone_id: [test]
            duration: "00:00:30"
          - zone_id: [test2]
            duration: "00:00:30"
```

Service call to adjust time
```
service: irrigation_unlimited.adjust_time
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_z7
  actual: "00:01:00"
```

debug log:
```
2023-06-02 01:15:28.358 DEBUG (MainThread) [custom_components.irrigation_unlimited] LOAD
2023-06-02 01:15:28.358 DEBUG (MainThread) [custom_components.irrigation_unlimited] STOP
2023-06-02 01:15:28.359 DEBUG (MainThread) [custom_components.irrigation_unlimited] START
2023-06-02 01:17:30.003 INFO (MainThread) [custom_components.irrigation_unlimited] EVENT [2023-06-02 01:17:30] controller: 1, zone: 0, state: 1
2023-06-02 01:17:30.004 INFO (MainThread) [custom_components.irrigation_unlimited] EVENT [2023-06-02 01:17:30] controller: 1, zone: 8, state: 1, data: 8.1.1.2.1
2023-06-02 01:18:00.008 INFO (MainThread) [custom_components.irrigation_unlimited] EVENT [2023-06-02 01:18:00] controller: 1, zone: 8, state: 0
2023-06-02 01:18:00.009 INFO (MainThread) [custom_components.irrigation_unlimited] EVENT [2023-06-02 01:18:00] controller: 1, zone: 0, state: 0
```

I observed that the start and end times in the schedules in the timeline are also not adjusted. Here the start time for the sequence was `01:37`.
I don't know why the zone `test2` has so many schedules with status `scheduled` in the timeline.
```
zone_id: test
index: 6
enabled: true
status: off
schedule_count: 0
schedules: 
adjustment: =0:01:00
current_schedule: null
percent_complete: 0
next_schedule: 1
today_total: 8.7
timeline: 
- start: '2023-06-03T23:37:00+00:00'
  end: '2023-06-03T23:38:00+00:00'
  schedule_name: Schedule 1
  adjustment: '=0:01:00'
  status: next
- start: '2023-06-01T23:13:30+00:00'
  end: '2023-06-01T23:14:00+00:00'
  schedule_name: Schedule 1
  adjustment: ''
  status: history
... [redacted]
```

```
zone_id: test2
index: 7
enabled: true
status: off
schedule_count: 0
schedules: 
adjustment: 
current_schedule: null
percent_complete: 0
next_adjustment: 
next_schedule: 1
next_name: Schedule 1
next_start: 2023-06-02T01:37:30+02:00
next_duration: 0:00:30
today_total: 11.5
timeline: 
- start: '2023-06-03T23:38:00+00:00'
  end: '2023-06-03T23:38:30+00:00'
  schedule_name: Schedule 1
  adjustment: ''
  status: scheduled
- start: '2023-06-03T23:37:30+00:00'
  end: '2023-06-03T23:38:00+00:00'
  schedule_name: Schedule 1
  adjustment: ''
  status: scheduled
- start: '2023-06-02T23:37:30+00:00'
  end: '2023-06-02T23:38:00+00:00'
  schedule_name: Schedule 1
  adjustment: ''
  status: scheduled
- start: '2023-06-01T23:37:30+00:00'
  end: '2023-06-01T23:38:00+00:00'
  schedule_name: Schedule 1
  adjustment: ''
  status: next
- start: '2023-06-01T23:33:30+00:00'
  end: '2023-06-01T23:34:00+00:00'
  schedule_name: Schedule 1
  adjustment: ''
  status: history
... [redacted]
```

I have also tested to adjust the time by a lower value than the scheduled, e.g. "00:00:25", but it had the same result.
