### ISSUE TITLE
Notification for irrigation_unlimited_switch_error, irrigation_unlimited_sync_error not working

### ISSUE THREAD

**Issue by Kurisutian** [rgc99/irrigation_unlimited#115]
**Describe the bug**
I've used the example for a notification on irrigation_unlimited_switch_error, irrigation_unlimited_sync_error as described in the documentation. However for some reason HA does have an issue with it:

```
Logger: homeassistant.components.automation.irrigation_unlimited_switch_error
Source: helpers/script.py:410
Integration: Automatisierung (documentation, issues)
First occurred: 4. Juni 2023 um 04:43:47 (13 occurrences)
Last logged: 08:10:37

Irrigation Unlimited Switch Error: Error executing script. Error for call_service at pos 1: Error rendering data template: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Irrigation Unlimited Switch Error: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'dict object' has no attribute 'event'
``` 

**To Reproduce**
1. Create the Automation from the docs
2. Wait for an sync error for a switch
3. Check the HA Logs

**Expected behavior**
A notification is being sent out

**Additional context**
Using shelly devices as switches it seems that for some reason the first one in the sequence fails quite often. It might however just be a coincidence.

**Comment by rgc99** [comment]
I have zigbee switches and not without dramas hence the whole check back thing. Perhaps the notification is for the controller which might produce the error. I have added a couple of lines to test the zone is valid. 
```yaml
automation:
  - id: "IU1653340138435"
    alias: "Irrigation Unlimited Switch Error"
    description: "Email a switch syncronisation error"
    trigger:
      - platform: event
        event_type:
          # - irrigation_unlimited_sync_error
          - irrigation_unlimited_switch_error
    action:
      - service: notify.NOTIFIER_NAME # Make sure this matches the "NOTIFIER_NAME" in the smtp setup
        data:
          title: "Irrigation Switch Error"
          message: |
            Type: {{ trigger.event.event_type }}
            Time: {{ as_local(trigger.event.time_fired).strftime('%c') }}
            Expected: {{ trigger.event.data.expected }}
            Controller: {{ trigger.event.data.controller.index + 1 }} {{ trigger.event.data.controller.name }}
            {% if trigger.event.data.zone.index is not none %}
              Zone: {{ trigger.event.data.zone.index + 1 }} {{ trigger.event.data.zone.name }}
            {% endif %}
            Entity: {{ trigger.event.data.entity_id }}
```
