### ISSUE TITLE
Using preamble and HASmartIrrigation 

### ISSUE THREAD

**Issue by Kurisutian** [rgc99/irrigation_unlimited#122]
## Version of the custom_component
2023.6.1
-->

## Configuration

```yaml

irrigation_unlimited:
  controllers:
    name: "Bewässerung Garten"
    enabled: true
    preamble: '00:01'
    postamble: '-00:01'
    all_zones_config:
      minimum: '00:01'
      maximum: '01:00'
      check_back:
        delay: 60
        retries: 4
    zones:
      - name: "Rasen"
        entity_id: "switch.bewasserung_rasen"
        show:
          timeline: true
      - name: "Beete"
        entity_id: "switch.bewasserung_beete"
        show:
          timeline: true
    sequences:
      - name: "Komplett (Sommer)"
        delay: "00:01"
        schedules:
          - name: "Fertig vor Sonnenaufgang"
            time:
              sun: "sunrise"
              before: "00:10"
            anchor: finish
            weekday: [mon, thu]
            month: [jun, jul, aug, sep]
        zones:
          - zone_id: 2  # Beete
            duration: "00:20"
          - zone_id: 1  # Rasen
            duration: "00:25"
    
      - name: "Beete (Sommer)"
        delay: "00:01"
        schedules:
          - name: "Fertig vor Sonnenaufgang"
            time:
              sun: "sunrise"
              before: "00:10"
            anchor: finish
            weekday: [tue, wed, fri, sat, sun]
            month: [jun, jul, aug, sep]
        zones:
          - zone_id: 2  # Beete
            duration: "00:20"
    
      - name: "Komplett (Früh-/Spätsommer)"
        delay: "00:01"
        schedules:
          - name: "Fertig vor Sonnenaufgang"
            time:
              sun: "sunrise"
              before: "00:10"
            anchor: finish
            weekday: [mon]
            month: [may, oct]
        zones:
          - zone_id: 1  # Rasen
            duration: "00:10"
          - zone_id: 2  # Beete
            duration: "00:05"
    
      - name: "Beete (Früh-/Spätsommer)"
        delay: "00:01"
        schedules:
          - name: "Fertig vor Sonnenaufgang"
            time:
              sun: "sunrise"
              before: "00:10"
            anchor: finish
            weekday: [wed, sat]
            month: [may, oct]
        zones:
          - zone_id: 2  # Beete
            duration: "00:05"

```

## Describe the bug
I currently use HASmartIrrigation to calculate the required watering times for two zones. In addition I have a preamble of one minute in the controller to automate turning on a pump if it's chosen as the selected source of the water. Now I noticed that when there was sufficient rain and the calculated watering times are zero the controller still turns on for 1 minute but no zone will run afterwards. So this would mean I turn on the waterpump for one minute but nothing happens with it as watering is not required. Also when this occurred I noticed a dropped sync error about the switch which was supposed to run but didn't as for the zero seconds calculation. 
Is there a way to tell IU that if the values for the next to come watering sequence are all zero, it will not turn on at all, not even for the preamble time of the controller?
