### ISSUE TITLE
Using irrigation_unlimited.adjust_time breaks further manual adjustments 

### ISSUE THREAD

**Issue by Kolia56** [rgc99/irrigation_unlimited#123]
Before any call to the service irrigation_unlimited.adjust_time, manual adjust works as expected. It can even be reset to the original value by wiping the value in the box.
However, as soon as the service  irrigation_unlimited.adjust_time is used, manual adjustment does not work anymore.

It shall be noticed that the service call put a comma before the equal sign in the box value. 
![image](https://github.com/rgc99/irrigation_unlimited/assets/20872098/232fe7d7-c30b-4c84-bf21-4f38cbbc1c20)

Running 2023.6.1 and card 2023.6.2

```
irrigation_unlimited:
  controllers:
    name: "Controleur 1"
    all_zones_config:
      show:
        timeline: true
      allow_manual: true
      duration: "0:10:00"
    zones:
      - name: Café François
        entity_id: switch.vanne_atelier_gui
      - name: Serre
        entity_id: switch.vanne_maison_journalier_gui
      - name: Pelouse
        entity_id : switch.vanne_jardin_devant_gui
      - name: Deux carrés
        entity_id: switch.vanne_deux_carres_gui
      - name: Un carré
        entity_id: switch.vanne_un_carre_gui
      - name: Petits fruits
        entity_id: switch.vanne_petits_fruits_gui
      - name: Haie - Céanothe - Fleurs
        entity_id: switch.vanne_haie_gui
      - name: Pommiers
        entity_id: switch.vanne_pommiers_gui
      - name: Pare-terre Julie 
        entity_id: switch.vanne_buanderie_grande_maison_gui
      - name : Haies pelouses
        entity_id: switch.718
      - name: If Cour carrée
        entity_id: switch.vanne_salle_claudine_gui
      - name: Haie du fond
        entity_id: switch.vanne_haie_fond_gui
      - name: Tilleul
        entity_id: switch.vanne_tilleul_gui
      # - name: Cuisine grande maison
      #   entity_id: switch.vanne_cuisine_grande_maison_gui
    sequences:
      - name: nuit
        delay: "00:01"
        schedules:
          - time: "22:00"
        zones:
          - zone_id: 1 # Café François
            duration: "00:30"
          - zone_id: 2 # Serre et autres
            duration: "00:20"
          - zone_id: 9 # Pare-terre Julie
            duration: "00:30"
          - zone_id: 4 # Deux carrés
            duration: "00:29"
          - zone_id: 5 # Un carré
            duration: "00:20"
          - zone_id: 6 # Petits fruits
            duration: "00:30"
          - zone_id: 7 # Haie - Céanothe
            duration: "00:40"
          - zone_id: 8 # Pommiers
            duration: "00:20"
          - zone_id: 10 # Haies pelouse
            duration: "00:25"
          - zone_id: 11 # If cour carrée
            duration: "00:10"
          - zone_id: 12 # Haie du fond
            duration: "00:30"            
          - zone_id: 13 # Tilleul - Cerisier
            duration: "00:30"            
      - name: jour
        duration: "00:05"
        delay: "01:55"
        repeat: 3
        schedules: 
          - time: "12:00"
        zones:
          - zone_id: 2
      - name: Pelouse seule (nuit)
        schedules:
          - time: 03:30
        zones:
          - zone_id: 3
            duration: "00:30"
```
```
service: irrigation_unlimited.adjust_time
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
  sequence_id: 3
  zones: 1
  actual: 0:40:00
```

**Comment by rgc99** [comment]
Sequences can have an adjustment within an adjustment; One for the zone element and another for the entire sequence. The adjustments are displayed as "sequence,zone". The above situation is correct as there is no sequence adjustment only a zone adjustment with a preceding comma.

If you had a sequence with three zones of durations 6,12,18 minutes and adjusted the first zone by 50% it would yield 3,12,18 minutes. Now adjust the entire sequence by 50% would produce 1.5,6,9.

To dig further I will also need the log, especially the 'CALL' messages.

**Comment by Kolia56** [comment]
Thank you for your feedback. Pretty tricky and smart. So, if I set blank in actual box of the zone in the sequence, it is reset as expected. In other words, when adjusting sequences either as a whole, or specific zones in the sequence, we must not set values at zone level. Is it correct?

Side question: is there a way to reset all sequences and zones in sequences as a whole? Call reload or something else?

Where do I get the logs? It is activated as per your instructions
```
logger:
  default: info
  logs:
    custom_components.irrigation_unlimited: debug
```
I see nothing in the system/log. Am I looking at a wrong place?

**Comment by rgc99** [comment]
If a sequence or any of its children has an adjustment then any adjustment on the actual zone are ignored. Personally I would not use schedules or adjustments on actual zones. Even if I wanted to run a single zone I would wrap it in a sequence, slightly more work but less confusing especially if there are many sequences in play.

Bulk reset. Target the controller `binary_sensor.irrigation_unlimited_c1_m` for example. Both `sequence_id:` and `zones:` take the magic number 0 which means all. `zones` also take a list like `[1,3,5]`.

For the logs go into Settings -> System -> Logs. In the search box put in `irrigation_unlimited` and press the `LOAD FULL LOGS` button. Copy and paste what is displayed.

**Comment by Kolia56** [comment]
Indeed, this is what I've done as soon I started to use sequence, I focused on adjusting them. I currently experiencing HA smartirrigation, pretty interesting to see whether I can really forget manual runs. I have a David Instruments VP2 station including evapotranspiration sensor. I'm concerned about integrating rain forecast that is to my point of view needed to avoid possible watering whereas raining is very likely to happen say in the next 12 hours. 

I tried that : "Bulk reset. Target the controller binary_sensor.irrigation_unlimited_c1_m for example. Both sequence_id: and zones: take the magic number 0 which means all. zones also take a list like [1,3,5]." with mitigate success

Here the code:
```
service: irrigation_unlimited.adjust_time
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
  sequence_id: 3
  zones: 1
  actual: 0
```
And the result, is it what is expected? Should not it be blanked? Which is the case in the zone area but not in the sequence area. Using the card, it works as expected. There might be a glitch here? I tried "0" as well with no success. As you see, zone in the sequence still displays =00:40:00 and the zone itself is blanked whereas it should display 00:30:00
![image](https://github.com/rgc99/irrigation_unlimited/assets/20872098/c7059d32-1d6b-456d-a724-a97f30571658)




Thanks for the load full log tip, I overlooked this one. Nothing to report so far.

**Comment by rgc99** [comment]
That is setting the adjustment to 0 seconds. The card checks if the input box is empty/blank and issues a `reset:`. Here is what it should look like:
```yaml
service: irrigation_unlimited.adjust_time
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
  sequence_id: 3
  zones: 0
  reset:
```
