### ISSUE TITLE
irrigation_unlimited.list_config service not available

### ISSUE THREAD

**Issue by u20p17** [rgc99/irrigation_unlimited#128]
Hi all,
I have set up Irrigation Unlimited and it seems to work fine:

My irrigation.yaml file looks like this:
```
 controllers:
   all_zones_config: # <= Add these three lines <─┐
     show: # <= to the configuration            <─┤
       timeline: true # <= for all zones        <─┘
   zones:
     - name: "Zone1"
       entity_id: "switch.zone_1"
     - name: "Zone2"
       entity_id: "switch.zone_2"
     - name: "Zone3"
       entity_id: "switch.zone_3"
     - name: "Zone4"
       entity_id: "switch.zone_4"
     - name: "Zone5"
       entity_id: "switch.zone_5"
     - name: "Zone6"
       entity_id: "switch.zone_6"
     - name: "Zone7"
       entity_id: "switch.zone_7"
     - name: "Zone8"
       entity_id: "switch.zone_8"
   sequences:
     - name: "Summer"
       duration: "00:05"
       delay: "00:01"
       schedules:
         - time: "05:30"
           weekday: [mon, wed, fri]
          month: [jun, jul, aug]
       zones:
         - zone_id: 1
         - zone_id: 2
         - zone_id: 3
         - zone_id: 4
         - zone_id: 5
         - zone_id: 6
         - zone_id: 7
         - zone_id: 8
     - name: "Winter"
       duration: "00:01"
       delay: "00:01"
       schedules:
         - time: "07:30"
           weekday: [sun]
           month: [dec, jan, feb]
       zones:
         - zone_id: 1
         - zone_id: 2
         - zone_id: 3
         - zone_id: 4
         - zone_id: 5
         - zone_id: 6
         - zone_id: 7
         - zone_id: 8
     - name: "Spring and Autumn"
       duration: "00:03"
       delay: "00:01"
       schedules:
         - time: "06:30"
           weekday: [mon, thu]
           month: [mar, apr, may, sep, oct, nov]
       zones:
         - zone_id: 1
         - zone_id: 2
         - zone_id: 3
         - zone_id: 4
         - zone_id: 5
         - zone_id: 6
         - zone_id: 7
         - zone_id: 8
```

Now I am trying to get the [manual_run](https://github.com/rgc99/irrigation_unlimited/tree/master#84-manual-run-card) and [enable/disable](https://github.com/rgc99/irrigation_unlimited/tree/master#85-enable-disable-card) cards to work and therefore I did the following:
1.) added to the config.yaml
```
homeassistant:
  packages: !include_dir_named packages
```
  2.) copied the following files to
```
/config/pyscript/irrigation_unlimited_service_shim.py
/config/packages/irrigation_unlimited_controls.yaml
```

When I now try to run the following automation i get the error, that the service is not available ( and I can indeed not see this service in the development tools...):

```
alias: Irrigation Unlimited Load UI Controls
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: irrigation_unlimited.list_config
    data:
      entity_id: input_select.irrigation_unlimited_entities
      section: entities
      first: <none>
  - service: irrigation_unlimited.list_config
    data:
      entity_id: input_select.irrigation_unlimited_sequences
      section: sequences
      first: <none>
mode: single

  
```

What I am doing wrong?

BR
