### ISSUE TITLE
Preamble  with negative value unpredictable

### ISSUE THREAD

**Issue by VaderZA** [rgc99/irrigation_unlimited#129]
First of all thanks for all your effort on this great project.

## Configuration
- I have the configuration for `Irrigation Unlimited` in a separate file with an include ref in configuration.yaml
- My system has a master pump which needs to be turned on after zone on and off before zone off (water hammer) like #73 
- Controller is a custom MQTT device
- Everything works as expected, except preamble

### postamble (for reference)
- works as expected:
- positive value == master off after zone off
- negative value == master off before zone off

### preamble
- positive value == master on before zone on
- negative value == master on before zone on, unless I enter a large value, then master follows zone immediately

As per #92 I had the same issue with preamble/postamble was 1 minute when using '00:01' for the value.
For me, `duration` options that give second resolution  -'00:00:02' and -2
But the master turns on and the zone immediately after, unless I set a higher preamble value. But event then there is no relation to the set value.
Not sure what impact granularity has here.
Appreciate your input

irrigation_unlimited.yaml file
```yaml
granularity: 1
sync_switches: false
controllers:
  - name: "Controller 1"
    enabled: true
    entity_id: "switch.pico_e6614103e7472324_irrigation_pump"
    preamble: '-00:00:02'
    postamble: '-00:00:02'
    all_zones_config:
      allow_manual: true
    zones:
      - name: "Front Flower Beds"
        entity_id: "switch.pico_e6614103e7472324_irrigation_zone_1"
        enabled: true
        duration: '00:05'
      - name: "Front Lawn"
        entity_id: "switch.pico_e6614103e7472324_irrigation_zone_2"
        enabled: true
        duration: '00:05'
      - name: "Front Lawn Side"
        entity_id: "switch.pico_e6614103e7472324_irrigation_zone_3"
        enabled: true
        duration: '00:05'
      - name: "Back Flower Beds Side"
        entity_id: "switch.pico_e6614103e7472324_irrigation_zone_4"
        enabled: true
        duration: '00:05'
      - name: "Back Lawn"
        entity_id: "switch.pico_e6614103e7472324_irrigation_zone_5"
        enabled: true
        duration: '00:05'
      - name: "Back Flower Beds Rear"
        entity_id: "switch.pico_e6614103e7472324_irrigation_zone_6"
        enabled: true
        duration: '00:05'
```
