### ISSUE TITLE
Watering History Information Card not working

### ISSUE THREAD

**Issue by Kurisutian** [rgc99/irrigation_unlimited#13]
**Describe the bug**
I'm using the watering history information card but despite using the dev.4 version of the mini-graph-card I do not get any information. The card only shows NaN for the minutes and no graph/bar at all.

**To Reproduce**
I'm using the following config:

```
type: 'custom:mini-graph-card'
name: Watering Last 7 Days
icon: 'mdi:sprinkler-variant'
entities:
  - entity: binary_sensor.irrigation_unlimited_c1_z1
    attribute: today_total
  - entity: binary_sensor.irrigation_unlimited_c1_z2
    attribute: today_total
show:
  graph: bar
  labels: true
unit: min
aggregate_func: max
hours_to_show: 168
group_by: date
lower_bound: 0
```

**Expected behavior**
A history graph with watering information shows

**Screenshots**
![image](https://user-images.githubusercontent.com/4199295/116521403-34f5f700-a8d4-11eb-9b77-9f3e8e876d50.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 88.0

**Smartphone (please complete the following information):**
 - Device: Pixel5
 - OS: Android 11
 - Browser Firefox 
 - Version 88.0

**Additional context**
I checked for the today_total attribute on both of my zones and they exist and contain a value. I also double-checked the custom cards and required integrations mentioned, all are installed. I did modify the automations and sensors to what I am using however nothing changed and this card does not work. I installed the preview version of the minigraph card (dev.4) so it should work. Also checked with the version mentioned in the docs (dev.3) but it also did not work.

**Comment by rgc99** [comment]
It almost looks like you are not recording the history. Try putting in a history card and see what you get.

```yaml
type: logbook
entities:
  - binary_sensor.irrigation_unlimited_c1_z1
  - binary_sensor.irrigation_unlimited_c1_z2
hours_to_show: 144
title: History
```

**Comment by Kurisutian** [comment]
Actually I do record history and it's working fine which is why I opened the bug. I checked for the sensors and everything should actually work which makes it weird. 

Here's a screenshot of the whole part of it:

![image](https://user-images.githubusercontent.com/4199295/116658168-daba6c00-a98f-11eb-85ed-1ba0e6dd00de.png)

Thanks!

**Comment by rgc99** [comment]
Please double check the version of mini-graph-card. I get the same result as you if I install v0.10.0. It must be v0.11.0-dev.3 or later where support for reading an attribute rather than the state was introduced.

**Comment by Kurisutian** [comment]
Checked it again but it's the correct version (>0.10.0):

![image](https://user-images.githubusercontent.com/4199295/116671996-ed3da100-a9a1-11eb-81e2-e404dfd20f00.png)

**Comment by rgc99** [comment]
Still feel it has something to do with the mini-graph-card. Let's try another graph card I have been experimenting with [apexcharts-card](https://github.com/RomRider/apexcharts-card)

```yaml
type: 'custom:apexcharts-card'
header:
  show: true
  title: Watering history
graph_span: 7d
all_series_config:
  type: column
  attribute: today_total
  group_by:
    duration: 1d
    func: last
    fill: zero
  show:
    as_duration: minute
span:
  start: day
  offset: '-7day'
series:
  - entity: binary_sensor.irrigation_unlimited_c1_z1
  - entity: binary_sensor.irrigation_unlimited_c1_z2
apex_config:
  tooltip:
    enabled: true
    x:
      format: dd MMM
  yaxis:
    title:
      text: minutes
```
