### ISSUE TITLE
New toggle service for manual run

### ISSUE THREAD

**Issue by luixal** [rgc99/irrigation_unlimited#133]
**Is your feature request related to a problem? Please describe.**
When using buttons/cards for manually start/stop irrigation, you usually end up calling a service using a template, like this one (using `custom-button-card`, javascript):

```yaml
tap_action:
  action: call-service
  service: |
    [[[
      return `irrigation_unlimited.${variables.sequence.status == 'on' ? 'cancel' : 'manual_run'}` ]]]
  service_data: |
    [[[
      if (variables.sequence.status == 'on') {
        return {
          entity_id: entity.entity_id
        }
      } else {
        return {
          entity_id: entity.entity_id,
          time: variables.irrigation_time
        }
      }
    ]]]
```

**Describe the solution you'd like**
Since `time` isn't required anymore when calling `manual_run`, it would be great to have a new serive (i.e: `toggle_run`) that starts/stops manual irrigation for a zone/sequence.

The above template will be something like this (no templating needed):

```yaml
tap_action:
  action: call-service
  service: irrigation_unlimited.toggle_run
  service_data:
    entity_id: binary_sensor.irrigation_unlimited_c1_z1,
    time: '00:03:00' # --> this would be only considered by the service when switching irrigation on
```

Would be nice (and maybe needed for some cases) that this service handles fields passed in service_data so you pass some fields, others or none.

**Describe alternatives you've considered**
The one described above inside a `custom-button-card` template.
