### ISSUE TITLE
Headers & Footers widget support

### ISSUE THREAD

**Issue by amzaldua** [rgc99/irrigation_unlimited#136]
Would it be possible to add support for "[headers and footers widgets](https://www.home-assistant.io/dashboards/header-footer/)" to this component's card, please?
Similar like this:
<img width="502" alt="Captura de pantalla 2023-09-19 a las 22 09 13" src="https://github.com/rgc99/irrigation_unlimited/assets/116205677/f4cc98ee-23fa-4958-8f69-8941b0d44382">

**Comment by rgc99** [comment]
What about putting the card into an [entities](https://www.home-assistant.io/dashboards/entities) card?
```yaml
type: entities
header: 
  type: picture
  image: "https://www.home-assistant.io/images/dashboards/header-footer/balloons-header.png"
entities:
  - type: custom:irrigation-unlimited-card
    name: Irrigation Unlimited
```
<img width="432" alt="Screen Shot 2023-09-20 at 8 25 04 am" src="https://github.com/rgc99/irrigation_unlimited/assets/13636007/ef14d15a-1989-45dc-8db4-d56739def8de">

**Comment by amzaldua** [comment]
The problem is the limited space for all the information displayed on the card. If we place it inside another card, the available space is further reduced. This is very noticeable on mobile devices. I made an initial attempt using the "Vertical Stack in a Card" component, and it looks good, but the dropdown menus get cut off. I'm attaching examples for reference.
By using [Vertical Stack In Card](https://github.com/ofekashery/vertical-stack-in-card#)
<img width="342" alt="Captura de pantalla 2023-09-20 a las 8 45 16" src="https://github.com/rgc99/irrigation_unlimited/assets/116205677/34c0e447-c531-4d26-97e0-5a755c207eda">

By using an entities card:
<img width="328" alt="Captura de pantalla 2023-09-20 a las 8 47 47" src="https://github.com/rgc99/irrigation_unlimited/assets/116205677/fd485dab-a4e4-45ea-b50a-61b075d46f47">
<img width="335" alt="Captura de pantalla 2023-09-20 a las 8 35 14" src="https://github.com/rgc99/irrigation_unlimited/assets/116205677/6a212a84-5c15-4a4a-94f8-6c7f9a3c17ea">

**Comment by amzaldua** [comment]
Ok, fixed. By using your solution along with CSS editing with the ["Card Mod"](https://github.com/thomasloven/lovelace-card-mod) compontent, I've been able to get it very close to what I was looking for. Attached screenshot and code.
<img width="389" alt="Captura de pantalla 2023-09-20 a las 9 07 00" src="https://github.com/rgc99/irrigation_unlimited/assets/116205677/26fc619d-365c-40ca-a44e-42738c2a5909">
```
type: entities
entities:
  - type: custom:irrigation-unlimited-card
    always_show_zones: false
    card_mod:
      style: |
        ha-card { border: none; }
header:
  type: picture
  image: /local/images/riego_2.png
  tap_action:
    action: none
  hold_action:
    action: none
title: Riego Jardín
```
Thanks for your help and support

**Comment by rgc99** [comment]
This might be even closer to what you are looking for.
```yaml
type: entities
entities:
  - type: custom:irrigation-unlimited-card
    always_show_zones: false
    card_mod:
      style: |
        ha-card { border: none; }
header:
  type: picture
  image: /local/images/riego_2.png
  tap_action:
    action: none
  hold_action:
    action: none
title: Riego Jardín
card_mod:
  style: |
    div.card-content { padding: 0; }
```
