### ISSUE TITLE
Error in readme ? days instead of weekday ? months instead of month

### ISSUE THREAD

**Issue by Antexa** [rgc99/irrigation_unlimited#14]
Hey ! 

You got an error in readme : 

```
# Run 15 min 3 times a week in summer, 10 min once a week in winter and twice a week in spring/autumn
irrigation_unlimited:
  controllers:
    zones:
      - entity_id: 'switch.my_switch_1'
        schedules:
          - time: '05:30'
            duration: '00:15'
            days: [mon, wed, fri]
            months: [dec, jan, feb]
          - time: '05:30'
            duration: '00:10'
            days: [sun]
            months: [jun, jul, aug]
          - time: '05:30'
            duration: '00:12'
            days: [mon, thu]
            months: [mar, apr, may, sep, oct, nov]
```

Days -> weekday
Months -> month

Cheers !
