### ISSUE TITLE
After cancelling sequence manual run zones keep that schedule

### ISSUE THREAD

**Issue by luixal** [rgc99/irrigation_unlimited#140]
**Describe the bug**
If I start a sequence manually and I cancel while running, current zone is stopped and next start is scheduled correctly, but following zones keep the schedule of the manual run.

Concrete example:

I have a sequence that irrigates 7 zones (8, 7, 4, 6, 6, 6 and 4 mins). I start it manually calling the `manual_run` service, let's say at 11:00 (my next automatic irrigation is scheduled at 22:00). While the first zone is running, I cancel irrigation using the `cancel` service. First zone stops irrigating and shows the next start correctly (22:00), but the other zones keep the schedule of the manual run (i.e: 11:09, 11:17, etc.).

It's only a visual matter, zones are not started on that schedule.

**To Reproduce**
1. Start a sequence calling the `manual_run` service like this:

```yaml
service: irrigation_unlimited.manual_run
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
  sequence_id: 0
```

3. While a zone is irrigating, cancel irrgation using the `cancel` service, like this:

```yaml
service: irrigation_unlimited.cancel
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
```

5. Current zone irrigation will stop.
6. Next zones will show they're schedule to run in a few minutes instead of the next automatic irrigation.
7. DIsable and enable the sequence and next start is back to normal in all zones.

**Expected behavior**
All zones show it's next start at the next scheduled irrigation.

**Screenshots**
I have my next irrigation scheduled at 22:00. It's 11:49 and I start that sequence manually, card shows this:

![image](https://github.com/rgc99/irrigation_unlimited/assets/615268/e547916b-817a-44e3-8503-b02f9c2fa807)

Now, a few seconds later, I cancel irrigation calling the `cancel` service. Zone 1 stops, but card shows this:

![image](https://github.com/rgc99/irrigation_unlimited/assets/615268/570bb7fe-1d27-4195-8c17-66cb05898013)

If I disable and enable the sequence, everything goes to normal:

![image](https://github.com/rgc99/irrigation_unlimited/assets/615268/1b32cc49-659a-4cab-9032-74e60946e60f)

**Irrigation Unlimited log file**
The config shown in the readme:

```yaml
logger:
  default: info
  logs:
    custom_components.irrigation_unlimited: debug
```

doesn't seem to work for me :(

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chrome
 - Version 117.0.5938.92

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20
 - OS: Android 13
 - Browser N/A
 - Version N/A

**Additional context**
