### ISSUE TITLE
Companion card possible error in start times for repeat sequences

### ISSUE THREAD

**Issue by evercape** [rgc99/irrigation_unlimited#146]
**Describe the bug**
Companion card shows incorrect start time.

**To Reproduce**
```
  irrigation_unlimited:
    controllers:
      - name: Lawn Areas
        zones:
          - name: "Lawn Berms"
            entity_id: switch.g0272_irrigation_lawn_front_of_berms
          - name: "Lawn Kitchen"
            entity_id: switch.g0273_irrigation_lawn_between_pool_and_kitchen
          - name: "Lawn Pool Tiles"
            entity_id: switch.g0280_irrigation_lawn_along_pool_tiling
          - name: "Lawn Guest Patio"
            entity_id: switch.g0386_irrigation_lawn_gh_pool_and_patio
          - name: "Lawn Guest Right"
            entity_id: switch.g0391_irrigation_gh_lawn_driveway_right
          - name: "Lawn Guest Left"
            entity_id: switch.g0392_irrigation_gh_lawn_driveway_left
        sequences:
          - name: "Lawn: Main House"
            duration: "00:15"
            repeat: 3
            schedules:
              - name: "Lawn 1"
                time: "05:30"
                anchor: start
                weekday: [mon, wed, fri]
                month: [oct, nov, dec, jan, feb, mar, apr]
            zones:
              - zone_id: 1
              - zone_id: 2
              - zone_id: 3
          - name: "Lawn: Guest House"
            duration: "00:15"
            repeat: 3
            schedules:
              - name: "Lawn 2"
                time: "05:30"
                anchor: start
                weekday: [tue, thu, sat]
                month: [oct, nov, dec, jan, feb, mar, apr]
            zones:
              - zone_id: 4
              - zone_id: 5
              - zone_id: 6
```

**Expected behavior**
The start times under each sequence should be correct - not sure where they come from. See screenshot in pink.

Whenever a sequence runs more than once, would be nice to indicate this on the companion card. 

**Screenshots**
![Notification_Center](https://github.com/rgc99/irrigation_unlimited/assets/4627761/101eb6e9-43ac-4ff4-9167-9ea5a7a88a32)

**Irrigation Unlimited log file**
Let me know if you require them.
