### ISSUE TITLE
HA Smart Irrigation automation - reset bucket only when 

### ISSUE THREAD

**Issue by Stan-Gobien** [rgc99/irrigation_unlimited#15]
Not an issue, rather an idea.
I'm using the HA Smart Irrigation integration and your automation example to adjust the run time of Irrigation Unlimited.
(I have a dripline system by the way, no sprinklers, but it's not really relevant)

Because it's raining a lot my Smart Irrigation bucket has filled quite a lot. For that reason the adjusted runtime is now 0 seconds. 
The automation example from the documentation here works fine, except that when the adjusted run time is 0 the next action still resets the bucket. Which brings the bucket back at 0. However since there was no run it shouldn't do that in my opinion. 
So my suggestion is to add a condition to the action 'reset bucket' only when sensor.smart_irrigation_daily_adjusted_run_time is > 0 so when a run will actually take place.

Furthermore I have set different schedules for Irrigation Unlimited according to the months. The automation for the adjust runtime is now triggered daily, but my irrigation only runs twice a week. So every night the runtime gets adjusted, and that's absolutely fine. But also every night the bucket gets reset even though no run might be scheduled for that night.

Can we add another conditon on the action and do the reset bucket only when a run (either manual or scheduled) will take place? Or do we split the automation and is it possible to trigger to reset the bucket only when irrigation unlimited does a run and the adjusted runtime is > 0 ?

PS: This is the automation I'm talking about.

```
- alias: Smart Irrigation
  description: Adjust watering times
  trigger:
  - platform: time
    at: 04:00
  action:
  - service: irrigation_unlimited.adjust_time
    data:
      entity_id: binary_sensor.irrigation_unlimited_c1_z1
      actual: >
        {% set t = states('sensor.smart_irrigation_daily_adjusted_run_time') | int %}
        {{ '{:02d}:{:02d}:{:02d}'.format((t // 3600) % 24, (t % 3600) // 60, (t % 3600) % 60) }}
  - service: smart_irrigation.smart_irrigation_reset_bucket
  mode: single
```

Thanks for the great integration!

**Comment by rgc99** [comment]
You are right, split the automation into two separate tasks; adjustment and bucket reset. I think [history_stats](https://www.home-assistant.io/integrations/history_stats) may be your friend here. First create a sensor to count the number of times the system was on yesterday and then an automation to reset the bucket if the system was on:

```yaml
sensor:
  - platform: history_stats
    name: Irrigation Unlimited yesterday run count
    entity_id: binary_sensor.irrigation_unlimited_c1_m
    state: “on” 
    type: count 
    end: "{{ now().replace(hour=0, minute=0, second=0) }}" 
    duration: 
      hours: 24 
 
automation: 
  - alias: HA Smart Irrigation reset bucket 
    trigger: 
    - platform: time
      at: 04:30
    condition:
      condition: numeric_state
      entity_id: sensor.irrigation_unlimited_yesterday_run_count
      above: 0
    action:
    - service: smart_irrigation.smart_irrigation_reset_bucket
    mode: single
````
Lots of possibilities here but hopefully this will get you going. Let me know how you get on so we share it.

**Comment by Stan-Gobien** [comment]
Hey, thanks for your answer.
So the idea is that we count the number of times irrigation unlimited has run in the past 24 hours (yesterday might be a misleading name). If the count is higher than 0, meaning it has run then we reset the bucket. 
Good idea.

The question is, when should we call the reset bucket automation?
Ideally it should be called right after the run has finished, but because of variable schedules that's a bit difficult.
The "sensor.smart_irrigation_daily_adjusted_run_time" gets calculated at 23h.
I'm pretty sure that the result of that calculation is very different depending on the value of the bucket.
So would it be best to run the automation at for instance 22h? 
So that the calculation at 23h will be with correct values.

**Comment by Stan-Gobien** [comment]
Considering if the run was perhaps at sunrise we still loose most of the day of raining or vaporization if we reset only at 22h in the evening.

So still not ideal. In my situation I can schedule the reset perhaps at 9h in the morning, because I will always schedule the automatic runs a bit before sunrise.

The best solution would be some kind of sensor "run finished" that changes from off to on on finish and could thus trigger the reset automation. Is that something that is possible perhaps?

**Comment by Stan-Gobien** [comment]
Just thinking a bit out loud here:

Could we not trigger the reset automation on the state attribute "Status" of "binary_sensor.irrigation_unlimited_c1_m" changing from 'on' to 'off'?

**Comment by rgc99** [comment]
Rereading the docs; calculations are done at 23:00 and the bucket should be reset after any irrigation so yes let's do that. Here is the complete automation.

```yaml
automation:
  - alias: Smart Irrigation adjustment
    description: Adjust watering times based on smart irrigation calculations
    trigger:
      - platform: time
        at: "23:30"
    action:
      - service: irrigation_unlimited.adjust_time
        data:
          entity_id: binary_sensor.irrigation_unlimited_c1_z1
          actual: >
            {% set t = states('sensor.smart_irrigation_daily_adjusted_run_time') | int %}
            {{ '{:02d}:{:02d}:{:02d}'.format((t // 3600) % 24, (t % 3600) // 60, (t % 3600) % 60) }}
    mode: single

  - alias: Smart Irrigation reset bucket
    description: Resets the Smart Irrigation bucket after watering
    trigger:
      - platform: state
        entity_id:
          # Add Irrigation Unlimited sensors here
          - binary_sensor.irrigation_unlimited_c1_m
        from: "on"
        to: "off"
    action:
      - service: smart_irrigation.reset_bucket
```
