### ISSUE TITLE
Check_back object with manual switching of actuators syncing UI zone objects

### ISSUE THREAD

**Issue by evercape** [rgc99/irrigation_unlimited#156]
Hi Robert,

I am possibly not fully understanding the `check_back` object. You recommended at some point that I set it to `states:none`.

What I am trying to do is the following:

1. Someone either presses the physical switch on the KNX actuator, or a KNX logic switches the corresponding irrigation actuator group address `1/1/0` state to `'on'` **without any interference with UI objects**
2. UI's zone entity, in this case `binary_sensor.irrigation_unlimited_c1_z1` should then automatically switch to 'on', ie be in sync.

Can you please advise if that is somehow already working? The way I understand the documentation [5.10](https://github.com/rgc99/irrigation_unlimited#510-check-back-object), this is a one way operation ie UI-->sync-->physical switches. However, it appears that it does not "work" the other way around, ie physical switch-->sync-->UI. Could you pls kindly confirm if my assumption is correct?

Happy to provide logs, but I think the issue is pretty clear from the above explanation and below sample config.

If it does not work as a bi-directional synchronisation (yet), then I should be able to sync the state by carrying the entity ID as [user attribute](switch.irrigation_knx_actuator_with_manual_switching_capability) and run some HASS automation.  What do you recommend?

thanks,
Martin 

(simplified) KNX and UI Yaml config:

```
pack_irrigation:
  knx:
    #SWITCH IRRIGATION VALVES
    switch:
      #LAWNS
       - name: "Irrigation KNX Actuator with manual switching capability"
        address: "1/1/0"
        state_address: "1/1/1"


irrigation_unlimited:
    history:
      span: 7
    refresh_interval: 5
    controllers:
      - name: Verges Road
        enabled: true
        check_back:
          states: none
        zones:
          - name: "Irrigation KNX Actuator with manual switching capability"
            entity_id: switch.irrigation_knx_actuator_with_manual_switching_capability
            user:
              entity_id: switch.irrigation_knx_actuator_with_manual_switching_capability

```
