### ISSUE TITLE
How to open to valves/zone at the same time

### ISSUE THREAD

**Issue by CiViC321** [rgc99/irrigation_unlimited#17]
Firstly, great component and thank you for sharing.

I have quite a big garden with multiple lanes/valves in the system.  I understand that a zone is equal to a switch.  How would I go about opening two valves/switch at the same time, or add two switches to a zone?

Thanks again.

**Comment by rgc99** [comment]
A controller/zone supports only one switch but it's a good idea to allow a list for this type of situation. Probably not that difficult to implement. In the meantime HA [group](https://www.home-assistant.io/integrations/group) might help, haven't tried it but should work.

**Comment by rgc99** [comment]
Possibly the smallest feature I have made. Turns out the HA service call accepts a CSV list. Just needed to let the string pass through config validation. One character, two if you count the same change at the controller level. The identity_id now takes a list separated by commas.

**Comment by miguelpucela** [comment]
Related to this, I'd like to make a sequence in which some of the zones run at the same time, but also sequentially.

For instance, a controller with 3 zones. The desired sequence would be:

- zone 1: 2 minutes.
- zone 2: 2 minutes.
- zone1+zone2: 5 minutes.
- zone3: 7 minutes.

I think that in the actual sequence implementation it cannot be done ... Am I right?

**Comment by rgc99** [comment]
I love this thread. Short answer, you are correct. Long answer, if we make the zone_id parameter in the sequence a CSV string like '1,2' then this might work. I am thinking something like this:
```yaml
irrigation_unlimited:
  controllers:
      zones:
        - name: "Zone 1"
        - name: "Zone 2"
        - name: "Zone 3"
      sequences:
        - name: "Run 1"
          duration: "00:02"
          delay: "00:01"
          schedules:
              time: "05:30"
          zones:
            - zone_id: 1
            - zone_id: 2
            - zone_id: 1,2
              duration: "00:05"
            - zone_id: 3
              duration: "00:07"
```
