### ISSUE TITLE
Store every_n_days in a helper to edit via dashboard

### ISSUE THREAD

**Issue by simionpetrus** [rgc99/irrigation_unlimited#179]
Would this be possible?
Also for start_n_days

**Comment by rgc99** [comment]
This could be done by setting up the required helpers and then have an automation which updates the schedule when they change. Schedules can be updated in Irrigation Unlimited with the [load_schedule](https://github.com/rgc99/irrigation_unlimited?tab=readme-ov-file#77-service-load_schedule) service (including `every_n_days` and `start_n_days`). One proviso is that changes made through this service call are NOT saved and will revert to the configuration.yaml if the integration is reloaded, HA is restarted etc. You would need to also fire the automation on a HA restart.

**Comment by hejjaat** [comment]
I would like to see such a possibility as well. Lawn should not be watered every day, but less freuqently with bigger doses. We should water them every n days, depending on the temperature (basically). I am irrigating every day only if the temperature is above 30 ºC, every 2 days if 25-30 ºC, below 25 ºC only every 3 days. So I need to change the `every_n_days` daily. If it not survives HA restart I an end up over/underwatering. It would be nice to have the option to set only the `every_n_days`, and it would count from the last active day, no need to calculate the `start_n_days`.

**Comment by rgc99** [comment]
You can see how long since the last state change. Work it into a template with your other parameters and set the adjustment to 0 or 100 percent.

```yaml
{{ now() - states.binary_sensor.irrigation_unlimited_c1_z1.last_changed }}
```

**Comment by hejjaat** [comment]
I just had the time to make the automation to calculate the start day. But I cannot pass thorugh the day and date whatever jinja format I try: 
```
action: irrigation_unlimited.load_schedule
data:
  schedule_id: lawn
  day:
    every_n_days: {{ states.input_number.lawn_irrigation_day_variable.state }}      
    start_n_days: {{ states.sensor.lawn_irrigation_next_day.state }}
```
result:
Not a parseable type for dictionary value @ data['day']['start_n_days']. Got None expected int for dictionary value @ data['day']['every_n_days']. Got None 
Could you please help me with this Robert?
