### ISSUE TITLE
Is it possible to run watering of several zones at once?

### ISSUE THREAD

**Issue by SuperMaximus1984** [rgc99/irrigation_unlimited#186]
My zones are associated with corresponding switches:
```
# Garden Irrigation
irrigation_unlimited:
  controllers:
    zones:
      - name: 'A (Zone1) - Front Area'
        entity_id: 'switch.a'
      - name: 'B (Zone2) - Neighbor Area'
        entity_id: 'switch.b'
      - name: 'C (Zone3) - Backyard Area'
        entity_id: 'switch.c'
      - name: 'D (Zone4) - Pool Area'
        entity_id: 'switch.d'
      - name: 'E (Zone5) - Garden Area'
        entity_id: 'switch.e'
      - name: 'F (Zone6) - Drip Irrigation'
        entity_id: 'switch.f'        
    sequences:
      - delay: '00:02'
        zones:
          - zone_id: 1
            duration: '00:25'
          - zone_id: 2
            duration: '00:25'
          - zone_id: 3
            duration: '00:45'
          - zone_id: 4
            duration: '00:45'
          - zone_id: 5
            duration: '00:08'
          - zone_id: 6
            duration: '00:20'
```
I need to combine running zone1+zone2, then zone3+zone4, and then zone5+zone6.
Surely I will set the same time for those "combined zones" cycles. How can I realize it using additional sequence configuration?

**Comment by rgc99** [comment]
Combing zones 1+2 and 3+4 is easy because they have the same duration. Zone 5+6 not so simple because of the different duration.

```yaml
# Garden Irrigation
irrigation_unlimited:
  controllers:
    zones:
      - name: 'A (Zone1) - Front Area'
        entity_id: 'switch.a'
      - name: 'B (Zone2) - Neighbor Area'
        entity_id: 'switch.b'
      - name: 'C (Zone3) - Backyard Area'
        entity_id: 'switch.c'
      - name: 'D (Zone4) - Pool Area'
        entity_id: 'switch.d'
      - name: 'E (Zone5) - Garden Area'
        entity_id: 'switch.e'
      - name: 'F (Zone6) - Drip Irrigation'
        entity_id: 'switch.f'        
    sequences:
      - delay: '00:02'
        zones:
          - zone_id: [1,2]
            duration: '00:25'
          - zone_id: [3,4]
            duration: '00:45'
          - zone_id: 5
            duration: '00:08'
          - zone_id: 6
            duration: '00:20'
```
