### ISSUE TITLE
Re-Install

### ISSUE THREAD

**Issue by sdebie** [rgc99/irrigation_unlimited#187]
## Version of the custom_component

VERSION = "2024.8.0"

## Configuration

```yaml

irrigation_unlimited:
  controllers:
    - name: "Controller 1"
      enabled: true # <= See example 1.0
      entity_id: "switch.8_pump"
      zones:
        - name: "C1 Front lawn"
          entity_id: "switch.1_front_lawn"

```

## Describe the bug

I had the Irrigation Unlimited Installed and worked perfectly, I decided to uninstall and do some cleanup, After Reinstalling everything I noticed "binary_sensor.irrigation_unlimited_c1_m" is missing, and now I'm unable to create Frontend for It

## Debug log

These messages are very important in helping to determine the problem. Go into Settings -> System -> Logs. In the search box put in `irrigation_unlimited` (Note the underscore between the two words) and press the **LOAD FULL LOGS** button. Copy and paste below.

```text

Not a bug.

```
