### ISSUE TITLE
If I add Sunday to the week day of a sequence, it does not work

### ISSUE THREAD

**Issue by pedromrg** [rgc99/irrigation_unlimited#189]
Hi there,

This is a weird thing that is happening.

First please check my config:
```
sequences:
  - name: "Relva"
    delay: "00:00:05"
    schedules:
      - name: "Sunrise"
        time:
          sun: "sunrise"
          before: "00:40"
        weekday: [mon, wed, sat]
    zones:
      - zone_id: 1
        duration: "00:15"
      - zone_id: 2
        duration: "00:15"
```

Problem is if I add sun for sunday ( weekday: [mon, wed, sat, sun] ) the sequence will not work !? Even in the front end it will not show any sheduled date for that sequence.

Is this happening to more of you?
