### ISSUE TITLE
Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe()

### ISSUE THREAD

**Issue by Kolia56** [rgc99/irrigation_unlimited#190]
## Configuration

```yaml

irrigation_unlimited:
    - name: "Controleur 1"
      all_zones_config:
        show:
          timeline: true
        allow_manual: true
        volume:
          entity_id: sensor.556
        # duration: "0:10:00"
          volume_scale: 1000
          flow_rate_scale: 60
          flow_rate_precision: 1
      zones:
        - name: Test
          zone_id: "1"
          # entity_id: switch.562
          enabled: false
          entity_id: switch.ev_id1
          # check_back:
          #   delay: 3
          #   retries: 1
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id1_ack
          maximum: "00:50:00"
        - name: Café François
          zone_id: "2"
          # entity_id: switch.562
          entity_id: switch.ev_id2
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id2_ack
          maximum: "00:50:00"
        - name: Serre
          zone_id: "3"
          # entity_id: switch.564
          entity_id: switch.ev_id3
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id3_ack
          maximum: "00:35:00"
        - name: If Cour carrée
          # entity_id: switch.565
          entity_id: switch.ev_id4
          zone_id: "4"
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id4_ack
          maximum: "00:20:00"          
        - name: Pare-terre Julie 
          zone_id: "6"
          # entity_id: switch.569
          entity_id: switch.ev_id6
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id6_ack
          maximum: "00:50:00"
        # - name: Pelouse
        #   zone_id: "7"
        #   # entity_id : switch.566
        #   entity_id : switch.ev_id7
        #   check_back:
        #     delay: 10
        #     retries: 3
        #     resync: true
        #     toggle: false
        #     entity_id: input_boolean.ev_id7_ack
        #   maximum: "01:00:00"
        - name: Deux carrés
          zone_id: "9"
          # entity_id: switch.713
          entity_id: switch.ev_id9
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id9_ack
          maximum: "00:50:00"
        - name: Un carré
          zone_id: "10"
          # entity_id: switch.714
          entity_id: switch.ev_id10
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id10_ack
          maximum: "00:30:00"
        - name: Petits fruits
          zone_id: "11"
          # entity_id: switch.715
          entity_id: switch.ev_id11
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id11_ack
          maximum: "00:50:00"
        - name: Haie - Céanothe - Fleurs
          zone_id: "12"
          # entity_id: switch.716
          entity_id: switch.ev_id12
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id12_ack
          maximum: "01:00:00"
        - name: Pommiers
          # entity_id: switch.717
          entity_id: switch.ev_id13
          zone_id: "13"
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id13_ack
          maximum: "00:50:00"

        - name: Haies pelouses
          zone_id: "14"
          # entity_id: switch.718
          entity_id: switch.ev_id14
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id14_ack
          maximum: "00:45:00"

        - name: Haie du fond
          zone_id: "15"
          # entity_id: switch.719
          entity_id: switch.ev_id15
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id15_ack
          maximum: "01:00:00"
        - name: Tilleul
          zone_id: "16"
          # entity_id: switch.720
          entity_id: switch.ev_id16
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id16_ack
          maximum: "00:50:00"
        - name: Bordure pelouse
          zone_id: "17"
          # entity_id: switch.720
          entity_id: switch.ev_id17
          # check_back:
          #   delay: 15
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id17_ack
          maximum: "00:40:00"
        - name: Circulaire pelouse
          zone_id: "18"
          # entity_id: switch.720
          entity_id: switch.ev_id18
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id18_ack
          maximum: "01:00:00"
        - name: Circulaire statue
          zone_id: "19"
          # entity_id: switch.720
          entity_id: switch.ev_id19
          # check_back:
          #   delay: 10
          #   retries: 3
          #   resync: true
          #   toggle: false
          #   entity_id: input_boolean.ev_id19_ack
          maximum: "01:00:00"
      sequences:
      - name: nuit
        enabled: true
        schedules:
          - name: 1
            time: "22:00"
            schedule_id: "s1"
        delay : 15
        zones:
          - zone_id: "2" # Café François (id2)
            duration: "00:30"
            # volume: 30
          - zone_id: "3" # Serre et autres (id3)
            duration: "00:15"
            # volume: 30
          - zone_id: "6" # Pare-terre Julie (id6)
            duration: "00:40"
            # volume: 20
          - zone_id: "9" # Deux carrés (id8)
            duration: "00:25"
          - zone_id: "10" # Un carré (id9)
            duration: "00:18"
          - zone_id: "11" # Petits fruits (id10)
            duration: "00:40"
          - zone_id: "12" # Haie - Céanothe (id11)
            duration: "00:40"
          - zone_id: "13" # Pommiers (id12)
            duration: "00:25"
          - zone_id: "14" # Haies pelouse (id13)
            duration: "00:20"
          - zone_id: "4" # If cour carrée (id4)
            duration: "00:10"
          - zone_id: "15" # Haie du fond (id15)
            duration: "00:25"            
          - zone_id: "16" # Tilleul - Cerisier (id16)
            duration: "00:25"    
          - zone_id: "17" # Bordure pelouse
            duration: "00:15"
            # volume: 150
          - zone_id: "18" # Pelouse (id7)
            duration: "00:20"
            # volume: 200
          - zone_id: "19" # circulaire statue
            duration: "00:20"
            # volume: 200
      - name: jour
        enabled: true
        duration: "00:05"
        delay: "03:25"
        repeat: 2
        schedules: 
          - name: 2
            time: "12:00"
            schedule_id: "s2"
        zones:
          - zone_id: 3

    - name: "Controleur 2"
      all_zones_config:
        show:
          timeline: false
        allow_manual: true
      zones:
        - name: Aérateur bac
          zone_id: "1"
          entity_id: switch.aerateur_bac
      sequences:
      - name: Bac
        schedules:
          - name: "bac"
            time: "07:00"
            schedule_id: "bac"
        zones:
          - zone_id: 1 # bac
            duration: "00:50"
            delay: "01:40"
            repeat: 6

```

## Describe the bug
The following error is logged repeatedly in the main log error journal. Both controllers are currently off.

## Debug log

These messages are very important in helping to determine the problem. Go into Settings -> System -> Logs. In the search box put in `irrigation_unlimited` (Note the underscore between the two words) and press the **LOAD FULL LOGS** button. Copy and paste below.

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/irrigation_unlimited/binary_sensor.py:334
integration: Irrigation Unlimited (documentation, issues)
First occurred: November 13, 2024 at 07:50:00 (20 occurrences)
Last logged: 17:50:30

Error doing job: Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 996, in _async_write_ha_state_from_call_soon_threadsafe
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/irrigation_unlimited/binary_sensor.py", line 334, in extra_state_attributes
    f"{current.current_zone.sequence_repeat + 1}/{self._sequence.repeat}"
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sequence_repeat'
```
