### ISSUE TITLE
Rain sensor not working 

### ISSUE THREAD

**Issue by vanwyklhf** [rgc99/irrigation_unlimited#191]
Good day
Firstly, Thank you for an awesome  application, works great..... except for my rain sensor, (Rainburd)
I've installed IU and the IU card and set up the zones and the automation. 
I have a normal open=>on , close==>off Switch to notify the system if it is raining or not and then if it is raining to switch off the irrigation until the switch turns off again and the schedule can continue. But it is not working. Can you please assist?

```
#Irrigation Schedule
irrigation_unlimited:
  controllers:
    - name: Main Controller
      entity_id: "switch.sonoff_1001dd52cf"
      zones: 
        - name: Lawn Street
          zone_id: "1"
          entity_id: "switch.sonoff_10023adba1_1"
        - name: Lawn Front
          zone_id: "2"
          entity_id: "switch.sonoff_10023adba1_2"  
        - name: Garden Front
          zone_id: "3"
          entity_id: "switch.sonoff_10023adba1_3"
        - name: Garden Back Door
          zone_id: "4"
          entity_id: "switch.sonoff_10023adba1_4"
        - name: Garden Back
          zone_id: "5"
          entity_id: "switch.sonoff_10023ad006_1"
        - name: Back Lawn 1
          zone_id: "6"
          entity_id: "switch.sonoff_10023ad006_2"
        - name: Back Lawn 2
          zone_id: "7"
          entity_id: "switch.sonoff_10023ad006_3"
        - name: Back Lawn 3
          zone_id: "8"
          entity_id: "switch.sonoff_10023ad006_4"
        - name: Pool
          zone_id: "9"
          entity_id: "switch.sonoff_1002204a79"
      sequences:
      - name: "Summer"
        duration: "00:15"
        delay: "00:01"
        schedules:
          - time: "05:30"
            weekday: [mon, wed, fri]
            month: [dec, jan, feb]
        zones:
          - zone_id: 3
          - zone_id: 5
      - name: "Winter"
        duration: "00:10"
        delay: "00:01"
        schedules:
          - time: "07:30"
            weekday: [sun]
            month: [jun, jul, aug]
        zones:
          - zone_id: 3
          - zone_id: 5
      - name: "Spring and Autumn"
        duration: "00:12"
        delay: "00:01"
        schedules:
          - time: "06:30"
            weekday: [mon, thu]
            month: [mar, apr, may, sep, oct, nov]
        zones:
          - zone_id: 3
          - zone_id: 5
      - name: "Daily"
        duration: "00:10"
        delay: "00:01"
        schedules:
          - time: "12:33"
            weekday: [sun, mon, tue, wed, thu, fri, sat]
            month: [jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec]
        zones:
            - zone_id: 4
```

```
automation:
  - alias: Rain Sensor
    trigger:
      platform: state
      entity_id:
        - binary_sensor.sonoff_10020b6c49
    action:
      service: irrigation_unlimited.adjust_time
      data:
        entity_id: binary_sensor.irrigation_unlimited_c1_z4
        percentage: >
          {% if states('binary_sensor.sonoff_10020b6c49') == 'on' %}
            {{ 100 }}
          {% else %}
            {{ 0 }}
          {% endif %}
```
