### ISSUE TITLE
How to variate time parameter of the manual_run

### ISSUE THREAD

**Issue by gerseit** [rgc99/irrigation_unlimited#2]
Hi!
Sorry for my rookie question!
I would like to dynamically change the Time parameter of the manual_run service. For example via an helper.
Could you send me any suggestions?
Regards: Tamas

**Comment by gerseit** [comment]
Thank you Miguel, I Will try it!

**Comment by gerseit** [comment]
Hi Miguel!
Your solution is perfect, thanx!
However, as you mentioned, I have to rollback to version 2021.3.16 because the manual run does not work in the newest version!
Regards: Tamas

**Comment by miguelpucela** [comment]
BTW, Tamas, if you have several controllers with several zones each and you want to use a single script to make the `manual_run` of each zone you have to make the next steps:

* Create one `input_number` for each controller. In my case, I have two controllers, called "pinar" and "pueblo". The names of them are: `input_number.timer_iu_manual_run_pinar` and `input_number.timer_iu_manual_run_pueblo`.
* Create another `input_number` to get the time of the actual zone you want to irrigate: `input_number.timer_iu_manual_run`. (This is the input_number I said in my previous post).
* Create one `input_text` to save the name of the zone to manual irrigate: `input_text.zone`.
* Create a button for each zone. For instance, for the first zone of the controller "pueblo":
```
type: button
tap_action:
  action: call-service
  service: script.manual_irrigation
  service_data:
    zone: c1_z1
    controller: pueblo
  target: {}
icon_height: 40px
icon: 'mdi:gesture-tap'
name: Manual irrigation zone 1
entity: binary_sensor.irrigation_unlimited_c1_z1
```
* Create a unique script to run each `manual_run` of each zone.
```
alias: Mannual irrigation
sequence:
  - service: input_text.set_value
    data_template:
      value: '{{ zone }}'
    target:
      entity_id: input_text.zone
  - service: input_number.set_value
    data_template:
      value: '{{ states("input_number.timer_iu_manual_run_" + place) }}'
    target:
      entity_id: input_number.timer_iu_manual_run
  - choose:  # if irrigation of zone is off, call manual_run
      - conditions:
          - condition: template
            value_template: >-
              {{ states("binary_sensor.irrigation_unlimited_" +
              states("input_text.zona")) == 'off' }}
        sequence:
          - service: irrigation_unlimited.manual_run
            data_template:
              entity_id: >-
                {{ "binary_sensor.irrigation_unlimited_" +
                states("input_text.zone") }}
              time: >-
                {{ ((states("input_number.timer_iu_manual_run") | float *
                60.0) | int) | timestamp_custom("%H:%M", False) }}
      - conditions: # if irrigation of zone is on, stop it, by disabling and enabling it.
          - condition: template
            value_template: >-
              {{ states("binary_sensor.irrigation_unlimited_" +
              states("input_text.zona")) == 'on' }}
        sequence:
          - service: irrigation_unlimited.disable
            data_template:
              entity_id: >-
                {{ "binary_sensor.irrigation_unlimited_" +
                states("input_text.zona") }}
          - service: irrigation_unlimited.enable
            data_template:
              entity_id: >-
                {{ "binary_sensor.irrigation_unlimited_" +
                states("input_text.zona") }}
    default: []
mode: restart
icon: 'mdi:sprinkler'
```
With the two conditions, the button is converted in a toggle button. If you press it while the irrigation is of (manual or scheduled), `manual_run` is called. If you press it while the irrigation is on, it's stopped.

Hope this helps.

BTW: In a similar way, you can make a toggle button and a script to make a sequential irrigation of all the zones of a controller.

**Comment by rgc99** [comment]
You might find this card useful. The main feature is it can handle as many controllers/zones as you wish by using an input_select entity. The items in the list are formatted like `c.z name` where c is the controller, z is the zone (0= master) followed by the friendly name. Here's how it looks.

![card_manual_run](https://user-images.githubusercontent.com/13636007/118386920-30fcff80-b65e-11eb-9137-b066fc91a0b9.png)

Select the zone from the dropdown list and press Go. Here is the card contents. Note: It uses [paper-buttons-rows](https://github.com/jcwillox/lovelace-paper-buttons-row) because it can create a button without the need for an actual entity.
```yaml
type: entities
title: Manual Run
entities:
  - entity: input_select.irrigation_unlimited_entities
    name: Controller/Zone
  - entity: input_datetime.irrigation_unlimited_run_time
    name: Time
  - type: divider
  - type: 'custom:paper-buttons-row'
    buttons:
      - name: Go
        tap_action:
          action: call-service
          service: script.irrigation_unlimited_manual_run
          service_data: null
      - name: Cancel
        tap_action:
          action: call-service
          service: script.irrigation_unlimited_cancel
          service_data: null
```
Now for the workings. I have the following in a file irrigation_unlimited_manual_run.yaml in the config/packages directory. The input_select and input_datetime could be done in configuration->helpers. The automation bit is optional but will auto populate the input_select on startup however you will also need the python_script shown below. Otherwise manually add your controllers and zones to the options of the input_select but make sure to follow the `c.z name` format. The two scripts are essential and are called from the card. The scripts decode the `c.z name` back into the actual entity i.e. `binary_sensor.irrigation_unlimited_c1_z1`

```yaml
# irrigation_unlimited_manual_run.yaml
# This is file should be located in config/packages directory
input_select:
  irrigation_unlimited_entities:
    name: Irrigation Unlimited Entities
    options:
      - <none>

input_datetime:
  irrigation_unlimited_run_time:
    name: Manual Run Time
    has_date: false
    has_time: true

automation:
  - alias: Irrigation Unlimited Load Entities
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: python_script.irrigation_unlimited_list_entities
      data:
        entity_id: input_select.irrigation_unlimited_entities

script:
  irrigation_unlimited_manual_run:
    alias: "Irrigation Unlimited Manual Run"
    mode: single
    variables:
      iu_entity: >
        {% set id = states('input_select.irrigation_unlimited_entities').split(' ')[0] %}
        {% set controller, zone = id.split('.') %}
        {% if zone == '0' %}
          {% set zone = 'm' %}
        {% else %}
          {% set zone = 'z' + zone %}
        {% endif %}
        {{ 'binary_sensor.irrigation_unlimited_c' + controller + '_' + zone }}

      iu_time: >
        {{ states('input_datetime.irrigation_unlimited_run_time') }}
    sequence:
      service: irrigation_unlimited.manual_run
      target:
        entity_id: "{{ iu_entity }}"
      data:
        time: "{{ iu_time }}"

  irrigation_unlimited_cancel:
    alias: "Irrigation Unlimited Cancel"
    mode: single
    variables:
      iu_entity: >
        {% set id = states('input_select.irrigation_unlimited_entities').split(' ')[0] %}
        {% set controller = 'c' + id.split('.')[0] %}
        {% set zone = id.split('.')[1] %}
        {% if zone == '0' %}
          {% set zone = 'm' %}
        {% else %}
          {% set zone = 'z' + zone %}
        {% endif %}
        {{ 'binary_sensor.irrigation_unlimited_' + controller + '_' + zone }}
    sequence:
      service: irrigation_unlimited.cancel
      target:
        entity_id: "{{ iu_entity }}"
```

This is the python_script called from the above automation to populate the input_select with all the irrigation unlimited controllers and zones. A python script is used instead of Jinja2 as it produces a list which Jinja2 is not capable of, many have tried...

```yaml
# irrigation_unlimited_list_entities.py
# This is a python script and should be located in config/python_scripts directory
#
# Description:
#   Populate the passed input_select entity with all
#   the irrigation_unlimited controllers and zones
#   The list will be formatted 'c.z Name'
#   Where:
#       c is the controller number (1..n)
#       z is the zone (0..n). 0 = master
#       Name is the friendly name
#
# Example output:
#   1.0 My Garden
#   1.1 Front Lawn
#   1.2 Vege Patch
#
# Parameters:
#   entity_id: Entity from the input_select domain
#
entity_id = data.get("entity_id", None)
if entity_id is not None and entity_id.split(".")[0] == "input_select":
    options = []
    for e in hass.states.entity_ids("binary_sensor"):
        domain, object_id = e.split(".")
        if object_id.startswith("irrigation_unlimited_c"):
            id = object_id.split("irrigation_unlimited_")[1]
            id = (
                id.replace("_", ".").replace("m", "0").replace("c", "").replace("z", "")
            )
            options.append(id + " " + hass.states.get(e).attributes["friendly_name"])
    service_data = {"entity_id": entity_id, "options": options}
    hass.services.call("input_select", "set_options", service_data, False)
```
Of course let me know if you have problems. I will roll all this up into the documentation and examples.
