### ISSUE TITLE
Questions about sequences

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation_unlimited#20]
Hello,

I'm starting my use of sequence and I have a couple of questions/sugestions:

* Is it possible to enable/disable a sequences in configuration? I don't think so.
* It would be also a good idea to have the parameteres 'weekday', 'day' and 'month' in the same way as in schedule objects.

If I'm right, it would be a great addition to apply these features to sequences, because at the end of the day, the result of schedules and sequences is the same, irrigation of the garden :)

Thank you for your time and great work!

Thank you for your time!

**Comment by rgc99** [comment]
There is no enable/disable for sequences but a good thought.
Schedules that are under zones and the schedules in sequences are one in the same. In fact they run the same code and have same features. The only difference is the duration parameter is ignored on sequences. This means weekday, day and month are available. Adapting the seasonal watering example in the readme for sequences (I haven't tested this so typos are possible):
```yaml
irrigation_unlimited:
  controllers:
      zones:
        - name: "Zone 1"
        - name: "Zone 2"
        - name: "Zone 3"
      sequences:
        - name: "Run 1"
          duration: "00:02"
          delay: "00:01"
          schedules:
            - name: "Summer"
              time: "05:30"
              weekday: [mon, wed, fri]
              month: [dec, jan, feb]
            - name: "Winter"
              time: '05:30'
              weekday: [sun]
              month: [jun, jul, aug]
            - name: "Spring and Autumn"
              time: '05:30'
              weekday: [mon, thu]
              month: [mar, apr, may, sep, oct, nov]
          zones:
            - zone_id: 1
            - zone_id: 2
              duration: "00:05"
            - zone_id: 3
              duration: "00:07"
```
Or if you wanted to run a different combination of zones and durations at different times of the year:
```yaml
irrigation_unlimited:
  controllers:
      zones:
        - name: "Zone 1"
        - name: "Zone 2"
        - name: "Zone 3"
      sequences:
        - name: "Summer"
          duration: "00:10"
          delay: "00:01"
          schedules:
            - time: "05:30"
              weekday: [mon, wed, fri]
              month: [dec, jan, feb]
          zones:
            - zone_id: 1
            - zone_id: 2
        - name: "Winter"
          duration: "00:02"
          delay: "00:01"
          schedules:
            - time: '05:30'
              weekday: [sun]
              month: [jun, jul, aug]
          zones:
            - zone_id: 2
            - zone_id: 3
        - name: "Spring and Autumn"
          duration: "00:05"
          delay: "00:01"
          schedules:
            - time: '05:30'
              weekday: [mon, thu]
              month: [mar, apr, may, sep, oct, nov]
          zones:
            - zone_id: 1
            - zone_id: 3
```
Many possibilities. Have fun.
