### ISSUE TITLE
HAsmartirrigation does not entirely work

### ISSUE THREAD

**Issue by Kurisutian** [rgc99/irrigation_unlimited#202]
**Describe the bug**
I've set up the HAsmartirrigation automation example based on the documentation. While adjustment of the watering times works, resetting the bucket does not. I have a total of 4 sequences and therefore had to make a small change to the conditions. However when the irrigation starts, it does not reset the bucket. Looking at the trace it shows, that the `"{{ trigger.event.data.schedule.index }}"` part does not seem to work. Weird thing is, that the condition indeed is not Empty or Null but still it renders the condition to false and therefor does not reset the bucket. 

**To Reproduce**
1. Set up the HAsmartirrigation automation based on the example provided
2. Have a sequence running.
3. Check if the bucket reset was running
4. For me it never runs because "{{ trigger.event.data.schedule.index }}" is false although it was no manual run

**Expected behavior**
Bucket shouls have been resetted

**Screenshots**
NONE

**Irrigation Unlimited log file**
Not relevant

**Additional context**
Here is the yaml of the automation which should reset the bucket but does not:

```yaml

alias: Smart Irrigation reset bucket Beete
description: Resets the Smart Irrigation bucket after watering
triggers:
  - trigger: event
    event_type: irrigation_unlimited_finish
conditions:
  - condition: template
    value_template: "{{ trigger.event.data.schedule.index }}"
  - condition: or
    conditions:
      - condition: template
        value_template: >-
          {{ trigger.event.data.entity_id ==
          'binary_sensor.irrigation_unlimited_c1_s1' }}
      - condition: template
        value_template: >-
          {{ trigger.event.data.entity_id ==
          'binary_sensor.irrigation_unlimited_c1_s2' }}
      - condition: template
        value_template: >-
          {{ trigger.event.data.entity_id ==
          'binary_sensor.irrigation_unlimited_c1_s3' }}
      - condition: template
        value_template: >-
          {{ trigger.event.data.entity_id ==
          'binary_sensor.irrigation_unlimited_c1_s4' }}
actions:
  - action: smart_irrigation.reset_bucket
    entity_id: sensor.smart_irrigation_beete
    data: {}
mode: single

```

Let me know if any other config or anything is needed. Thanks!
