### ISSUE TITLE
Maximum parameter not taken into account

### ISSUE THREAD

**Issue by rmeekers** [rgc99/irrigation_unlimited#21]
I've set the maximum parameter on the configuration:

```
irrigation_unlimited:
  granularity: 10
  refresh_interval: 20
  controllers:
    - name: 'Rain Bird'
      zones:
        - name: "Front (zone 1)"
          entity_id: "switch.rain_valve_1"
          maximum: "01:30"
        - name: "Back (zone 2)"
          entity_id: "switch.rain_valve_2"
          maximum: "06:00"
```

But when the run time is overwritten via `adjust_time` (coming from _HAsmartirrigation_), it doesn't respect the maximum run time.

Is this a bug, or is there something wrong in the configuration?

**Comment by rgc99** [comment]
This feature along with minimum was never fully implemented. It was overlooked in favour of its namesake in the adjust_time service call. There is merit in its completion as a guard against wayward service calls like a manual run for 3 hours instead of 3 minutes. Until it is finished there are a couple of workarounds. Use the maximum option in the adjust_time service call or use the jinja2 min() function in the script. Here is showing both methods, probably just need to choose one (untested).
```yaml
    action:
      - service: irrigation_unlimited.adjust_time
        data:
          entity_id: binary_sensor.irrigation_unlimited_c1_z1
          actual: >
            {% set t = states('sensor.smart_irrigation_daily_adjusted_run_time') | int %}
            {% set t = min(t, <SOME MAX VALUE IN SECONDS>)
            {{ '{:02d}:{:02d}:{:02d}'.format((t // 3600) % 24, (t % 3600) // 60, (t % 3600) % 60) }}
          maximum: "06:00"
```
