### ISSUE TITLE
Bug in configuration (testing parameter)

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation_unlimited#22]
In last version (v2021.06.15) testing object gives an error.

Configuration:

```
  granularity: 10
  refresh_interval: 30
  testing:
    enabled: false
    speed: 20.0
    times:
      - name: 'Test 1'
        start: '2021-03-01 08:30'
        end: '2021-04-30 07:30'
      - name: 'Test 2'
        start: '2021-01-01 05:00'
        end: '2021-01-01 05:30'
```

Gives the next error:

```
Invalid config for [irrigation_unlimited]: expected a list for dictionary value @ data['irrigation_unlimited']['testing']['results']. Got None
required key not provided @ data['irrigation_unlimited']['controllers'][0]['zones']. Got None. (See /config/configuration.yaml, line 19).
```

**Comment by rgc99** [comment]
Add two lines to the bottom something like the following:
```yaml
  granularity: 10
  refresh_interval: 30
  testing:
    enabled: false
    speed: 20.0
    times:
      - name: 'Test 1'
        start: '2021-03-01 08:30'
        end: '2021-04-30 07:30'
      - name: 'Test 2'
        start: '2021-01-01 05:00'
        end: '2021-01-01 05:30'
    results:
      - {t: '2021-03-01 08:30:00', c: 1, z: 0, s: 1}
```
The results section was supposed to be optional but I didn't get it quite right. It is undocumented at the moment as it may change. FYI, this is used for a holistic testing regime to match switch timings with a list of expected results, t=time, c=controller, z=zone(0=master), s=state(0=off, 1=on). Don't worry too much as it just logs a warning message.
