### ISSUE TITLE
I would like to send a mqtt command to run sprinklers

### ISSUE THREAD

**Issue by Gomeyy** [rgc99/irrigation_unlimited#28]
**Is your feature request related to a problem? Please describe.**
I want my valve controller to handle the timings incase there is an issue with home assistant

**Describe the solution you'd like**
The ability to send mqtt commands with time to run included

**Describe alternatives you've considered**
If you could point me in the right direction as to where to add custom run code I would happily work on it myself

**Comment by rgc99** [comment]
In the repository find the file custom_components/irrigation_unlimited/irrigation_unlimited.py. There are two points of interest IUController>call_switch() (line 1846) and IUZone>call_switch() (line 1171). This is where HA is called to turn on/off the valves.

What about creating an automation that tracks the controller/zone state? When it turns `on` take the `current_duration` attribute and send out the mqtt command. For example:

~~~yaml
  - alias: IU Turn on
    description: Send out mqtt command to valve
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.irrigation_unlimited_c1_z1
        from: "off"
        to: "on"
    action:
      - service: <send the command to mqtt. The time is in the current_duration attribute of the entity_id>
~~~

**Comment by Gomeyy** [comment]
Ahhh thank you, I didn't think of that. Love the functionality so far thanks for doing so much work.

**Comment by rgc99** [comment]
Glad to help. Please share your final automation so we can help others in the same situation.

**Comment by crazyfx1** [comment]
I had the same requirement and used the info here to put together following automation action.

I was hoping there is better way to access the duration but it seems like it's a string which I have to parse first and then go through the hassle of getting out the total seconds.

```YAML
- alias: Send time 4
  trigger:
  - platform: state
    entity_id: binary_sensor.irrigation_unlimited_c1_z4
    from: 'off'
    to: 'on'
  action:
  - service: number.set_value
    data:
      value: '{% set t = strptime(state_attr(''binary_sensor.irrigation_unlimited_c1_z4'',
        ''current_duration'') , ''%H:%M:%S'').time() %}{{ ((t.hour * 60 + t.minute)
        * 60 + t.second) }}'
    target:
      entity_id: number.time_4
```
