### ISSUE TITLE
Strange sequence behaviour

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation_unlimited#29]
Hello,

I'm having problems with sequences. I'm using version 2021.6.15.

I have the next configuration:

```
    - name: 'Riego Pinar'
      entity_id: 'switch.sonoff_1000aa7cb2'
      enabled: true
      zones:
       - name: 'Zona 1'
         enabled: true
         minimum: '00:00'
         maximum: '00:19'
         entity_id: 'switch.sonoff_10007802f0'
       - name: 'Zona 2'
         enabled: true
         minimum: '00:00'
         maximum: '00:19'
         entity_id: 'switch.sonoff_1000794f0b'
       - name: 'Zona 3'
         entity_id: 'switch.sonoff_1000049a5e'
         enabled: true
         minimum: '00:00'
         maximum: '00:19'
      sequences:
        - name: 'Secuencia Pinar'
          duration: '00:08'
          delay: '00:01'
          schedules:
            - name: 'Amanecer'
              time:
                sun: 'sunrise'
                after: '00:00'
              month: [mar, apr, may, jun, jul, aug, sep]
            - name: 'Después del anochecer'
              time:
                sun: 'sunset'
                after: '00:30'
              month: [mar, apr, may, jun, jul, aug, sep]
          zones:
            - zone_id: [2,3]
            - zone_id: 1
```

The result is that sometimes the sequence is not run completely and sometimes it is. The behaviour seems a bit random.

I don't know if you can reproduce it or somehow I can send you some log, so you can debug it.

Thank you and best regards.
Miguel
