### ISSUE TITLE
Watering graph not working

### ISSUE THREAD

**Issue by Hole23** [rgc99/irrigation_unlimited#31]
Hi guys.
I'm having trouble replicating the "Watering last 7 days" graph. My system is working and I updated to the latest version. All the other cards are working, though I'm learning to use HA and I'm a noob with this.

The problem is that when I use the code published for that graph it doesn't plot the data but writes "Not a number". I checked in the entities menu and I verified the attribute "today total" is present and is a number.

This is my code for the graph:

```
type: 'custom:mini-graph-card'
name: Watering Last 7 Days
icon: 'mdi:sprinkler-variant'
entities:
   -entity: binary_sensor.irrigation_unlimited_c1_z1
    attribute: today_total
show:
  graph: bar
  labels: true
unit: min
aggregate_func: max
hours_to_show: 168
group_by: date
lower_bound: 0
```

I also checked for the working principles of the mini-graph-card and using the "state_map" function to convert the binary sensor data works well. The graph though is not so good using this function (I think it approximates the "0" and "1" states resulting in a flat zero plot). Obviusly I'm here writing because I would like a bar graph proportional to the timings of watering.

![image](https://user-images.githubusercontent.com/87143798/128499893-67ed75f5-d4bc-40b9-b034-d84e708c2527.png)
