### ISSUE TITLE
State count of binary sensors vey high

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation_unlimited#4]
Hello,

I've checked the state count of my entities and found that irrigation unlimited binary sensors have the highest state count (much higher than the rest of entities).

I record states for the last 14 days:

```
recorder:
  purge_keep_days: 14 # Keep 14 days in history after purging @ 04:12
```

My irrigation unlimited configuration has 2 controllers with 3 and 4 zones each. This is my configuration:

```
granularity: 10
testing:
  enabled: false
  speed: 30.0
  times:
    - name: 'Test 1'
      start: '2021-03-01 08:30'
      end: '2021-04-30 07:30'
    - name: 'Test 2'
      start: '2021-01-01 05:00'
      end: '2021-01-01 05:30'
controllers:
  - name: 'Riego pueblo'
    enabled: true
    zones:
     - name: 'Zona 1'
       enabled: true
       minimum: '00:00'
       maximum: '00:10'
       entity_id: 'switch.sonoff_1000cade2e_1'
       schedules:
         - name: 'Primavera'
           time:
              sun: 'sunrise'
              after: '00:00'
           duration: '00:08'
           month: [mar, apr, may]
     - name: 'Zona 2'
       enabled: true
       minimum: '00:00'
       maximum: '00:10'
       entity_id: 'switch.sonoff_1000cade2e_2'
       schedules:
         - name: 'Primavera'
           time:
              sun: 'sunrise'
              after: '00:10'
           duration: '00:08'
           month: [mar, apr, may]
     - name: 'Zona 3'
       entity_id: 'switch.sonoff_1000cade2e_3'
       enabled: true
       minimum: '00:00'
       maximum: '00:10'
       schedules:
         - name: 'Primavera'
           time:
              sun: 'sunrise'
              after: '00:20'
           duration: '00:08'
           month: [mar, apr, may]
  - name: 'Riego Pinar'
    entity_id: 'switch.sonoff_1000aa7cd2'
    enabled: true
    zones:
     - name: 'Zona 1'
       enabled: true
       minimum: '00:00'
       maximum: '00:20'
       entity_id: 'switch.sonoff_100078d1f0'
       schedules:
         - name: 'Primavera'
           time: '03:00'
           duration: '00:12'
           month: [mar, apr, may]
     - name: 'Zona 2'
       enabled: true
       minimum: '00:00'
       maximum: '00:20'
       entity_id: 'switch.sonoff_100079df0a'
       schedules:
         - name: 'Primavera'
           time: '03:12'
           duration: '00:12'
           month: [mar, apr, may]
     - name: 'Zona 3'
       entity_id: 'switch.sonoff_100004da4e'
       enabled: true
       minimum: '00:00'
       maximum: '00:20'
       schedules:
         - name: 'Primavera'
           time: '03:12'
           duration: '00:12'
           month: [mar, apr, may]
     - name: 'Zona 4'
       entity_id: 'switch.sonoff_100078dfde'
       enabled: true
       minimum: '00:00'
       maximum: '00:20'
       schedules:
         - name: 'Primavera'
           time: '03:24'
           duration: '00:12'
           month: [mar, apr, may]
```

I get the these state counts:

```
* binary_sensor.irrigation_unlimited_c2_m: 20946
* binary_sensor.irrigation_unlimited_c1_m: 11418
* binary_sensor.irrigation_unlimited_c2_z1: 7735
* binary_sensor.irrigation_unlimited_c2_z2: 6757
* binary_sensor.irrigation_unlimited_c2_z3: 6757
* binary_sensor.irrigation_unlimited_c2_z4: 5985
* binary_sensor.irrigation_unlimited_c1_z1: 4116
* binary_sensor.irrigation_unlimited_c1_z3: 4000
* binary_sensor.irrigation_unlimited_c1_z2: 3929
```

Are all of these states necessary for this integration of am I making somethind wrong?  Or maybe it's due to the low value of the granularity?
