### ISSUE TITLE
Visualising changes to adjust_time in dashboard

### ISSUE THREAD

**Issue by tbaumann** [rgc99/irrigation_unlimited#44]
I think I got a pretty good adjustment workflow going. And I use your average sensor trick to display the rainfall and temps over last few days.

I think it would be nice if the adjustment percentage (or time) could be plotted ontop of that. But the value doesn't seem to be accessible to the UI. (Or at least I don't know how)

The default card accesses that value via some Attribute. But I don't have access to that via the sensor graph..

Any ideas or hints?

**Comment by rgc99** [comment]
The adjustment is in the zone entity attributes i.e. `binary_sensor.irrigation_unlimited_c1_z1`. There are a couple to choose from. The attribute `adjustment` shows adjustments made to the zone entity. The attribute `current_adjustment` shows the adjustment in play be it a sequence or zone. This attribute only shows while the zone is on. The `next_adjustment` is similar and shows the adjustment for the next schedule. This is the one I think would be the best.

In all cases the adjustment is formatted with the first character indicating the type of adjustment followed by the value. Adjustment type is `%` for percentage, `=` for actual/new time, `+` time increase and `-` for time decrease. You will most likely have to strip off the first character to chart it. Probably the best way would be to create a template sensor. Here you can get the attribute, manipulate and display it as a state. From there you should be able to chart it.

You might also be able to apexcharts-card which has some data manipulation capabilities. Here is a temperature card I have been playing around with:
```yaml
type: custom:apexcharts-card
header:
  show: true
  title: Temperature 5 days
  show_states: true
  colorize_states: true
graph_span: 5d
span:
  end: day
all_series_config:
  group_by:
    duration: 1d
    fill: zero
series:
  - entity: sensor.wupws_temp
    name: Min
    group_by:
      func: min
  - entity: sensor.wupws_temp
    name: Avg
    group_by:
      func: avg
  - entity: sensor.wupws_temp
    name: Max
    group_by:
      func: max
  - entity: sensor.bom_temp_max_0
    name: Forecast
    group_by:
      func: avg
yaxis:
  - decimals: 0
    apex_config:
      title:
        text: degrees C
apex_config:
  tooltip:
    enabled: true
    x:
      format: dd MMM
```

**Comment by tbaumann** [comment]
I think I get it. Attributes aren't really usable that way. But I can turn them into sensor values.

Thanks

**Comment by rgc99** [comment]
Some integrations can use attributes and even support templating, it depends. Here is an example to create a sensor from the adjustment attribute. Assumes you are using percentage adjustment method. Should end up with a sensor with the percentage as the state.

```yaml
sensor:
  - platform: template
    sensors:
      iu_adjustment_c1_z1:
        value_template: "{{ state_attr('binary_sensor.irrigation_unlimited_c1_z1', 'next_adjustment')[1:] }}"
        friendly_name: "Irrigation Unlimited Adjustment C1 Z1"
        unit_of_measurement: '%'
        icon_template: mdi:wrench-clock
```
