### ISSUE TITLE
Error in documentation under 'Service call access roadmap'

### ISSUE THREAD

**Issue by nirnachmani** [rgc99/irrigation_unlimited#48]
## Version of the custom_component
 N/A

## Configuration

```yaml

N/A

```

## Describe the bug
The following examples in the main page under "Service call access roadmap" should demonstrate 'adjust_time' but accidentally demonstrate 'enable':

```yaml

# Example 1.1.1 -> controller 1 -> zone 1 -> duration. This will alter the duration for zone 1.
- service: irrigation_unlimited.enable
  data:
    entity_id: binary_sensor.irrigation_unlimited_c1_z1

# Example 1.2.1 -> controller 1 -> zone 1 -> duration. This will alter the duration for zone 2.
- service: irrigation_unlimited.enable
  data:
    entity_id: binary_sensor.irrigation_unlimited_c1_z2
```

## Debug log

```text

N/A

```
