### ISSUE TITLE
Controller status during sequence delay

### ISSUE THREAD

**Issue by mdewyer** [rgc99/irrigation_unlimited#5]
First of all, excellent work on this project!

**Is your feature request related to a problem? Please describe.**

- When the controller is on the delay between zones in a sequence, the status of the controller changes to `Off`, which doesn't fully represent the situation. (A quick glance at its status during this time could lead you to believe it's not running at all, rather than just in-between zones.)

**Describe the solution you'd like**

- Maybe having the controller's status be something like `Delay` while delayed would work?

**Describe alternatives you've considered**

- As-is, basing an automation or Node-RED flow on the status of the controller would require making sure the status remains `Off` for more than the length of the delay, to be sure the system is actually off, off.

**Additional context**

- Version: 2021.3.29
- Test code:
```
irrigation_unlimited:
  controllers:
    zones:
      - zone_id: 1
        name: "Irrigation Zone 1"
        entity_id: "switch.irrigation_zone_1"
      - zone_id: 2
        name: "Irrigation Zone 2"
        entity_id: "switch.irrigation_zone_2"
      - zone_id: 3
        name: "Irrigation Zone 3"
        entity_id: "switch.irrigation_zone_3"
      - zone_id: 4
        name: "Irrigation Zone 4"
        entity_id: "switch.irrigation_zone_4"
    sequences:
      - name: "Everything"
        delay: "00:01"
        schedules:
          - name: "Morning - Every Day"
            time: "06:00"
            weekday: [mon, tue, wed, thu, fri, sat, sun]
        zones:
          - zone_id: 1
            duration: "00:01"
          - zone_id: 2
            duration: "00:01"
          - zone_id: 4
            duration: "00:01"
```
