### ISSUE TITLE
Wrong duration

### ISSUE THREAD

**Issue by asvel78** [rgc99/irrigation_unlimited#51]
i’m in trouble with the duration time, i saw the issue when i use the manual card on my lovelace dashboard.
i'm using the last version download by HACS

this is my configuration

```
#### IRRIGAZIONE ####
irrigation_unlimited:
  controllers:
    - name: 'Giardino Fronte Casa'
      enabled: true
      zones:
        - name: 'Zona Laghetto'
          entity_id: 
            - switch.sonoff_1000f46e4e_1
            - switch.sonoff_1000f46e4e_2
        - name: 'Zona pozzo'
          entity_id: 
            - switch.sonoff_1000f46e4e_3
            - switch.sonoff_1000f46e4e_4
      sequences:
        - delay: '00:01'
          name: 'Stagionale'
          schedules:
           # - name: 'Sunrise'
           #   time:
           #    sun: 'sunrise'
            - name: 'Inverno'
              time: '05:30'
              weekday: [mon, wed, fri]
              month: [dec, jan, feb]
              duration: '00:03'
            - name: 'Estate'
              time: '05:30'
              weekday: [sun]
              month: [jun, jul, aug]
              duration: '00:05'
            - name: 'Primavera e Autunno'
              time: '05:30'
              weekday: [mon, thu]
              month: [mar, apr, may, sep, oct, nov]    
              duration: '00:03'
          zones:
            - zone_id: 1
            - zone_id: 2
#### IRRIGAZIONE - FINE####
```
as you can see the duration is 5 or 3 minutes for each zone

The adjusting service mark a percentage of adjusting of %47.0 so the duration sould be 2 minutes and 35 seconds not 40 minutes
what is wrong in my irrigation?
![hassio1](https://user-images.githubusercontent.com/76561249/156362669-9f2fc158-6a67-4baf-9cd5-60cb1cde736e.png)

![hassio2](https://user-images.githubusercontent.com/76561249/156362646-d475f473-9cc5-4237-a1b1-e33596b72369.png)

Thanks in advance

**Comment by rgc99** [comment]
You don't have any durations setup for the zones. For now, move the `duration` setting in the schedules to the `zones:` section.

```yaml
irrigation_unlimited:
  controllers:
    - name: 'Giardino Fronte Casa'
      enabled: true
      zones:
        - name: 'Zona Laghetto'
          entity_id: 
            - switch.sonoff_1000f46e4e_1
            - switch.sonoff_1000f46e4e_2
        - name: 'Zona pozzo'
          entity_id: 
            - switch.sonoff_1000f46e4e_3
            - switch.sonoff_1000f46e4e_4
      sequences:
        - delay: '00:01'
          name: 'Stagionale'
          schedules:
           # - name: 'Sunrise'
           #   time:
           #    sun: 'sunrise'
            - name: 'Inverno'
              time: '05:30'
              weekday: [mon, wed, fri]
              month: [dec, jan, feb]
            - name: 'Estate'
              time: '05:30'
              weekday: [sun]
              month: [jun, jul, aug]
            - name: 'Primavera e Autunno'
              time: '05:30'
              weekday: [mon, thu]
              month: [mar, apr, may, sep, oct, nov]    
          zones:
            - zone_id: 1
              duration: '00:03'
            - zone_id: 2
              duration: '00:03'
```
Try the above, it should work. The default run time is 6 minutes (3+3). Now put back the `duration` in the schedules but note that the time specified is the TOTAL run time. Perhaps in summer you would like to run the system for 10 minutes so the value would be '00:10'. This will proportion the time across the zones and now give you 5 minutes for each zone.

**Comment by asvel78** [comment]
Hi rgc99, i tried without success.

```
#### IRRIGAZIONE ####
irrigation_unlimited:
  controllers:
    - name: 'Giardino Fronte Casa'
      enabled: true
      zones:
        - name: 'Zona Laghetto'
          entity_id: 
            - switch.sonoff_1000f46e4e_1
            - switch.sonoff_1000f46e4e_2
        - name: 'Zona pozzo'
          entity_id: 
            - switch.sonoff_1000f46e4e_3
            - switch.sonoff_1000f46e4e_4
      sequences:
        - delay: '00:01'
          name: 'stagioni'
          schedules:
           # - name: 'Sunrise'
           #   time:
           #    sun: 'sunrise'
            - name: 'Inverno'
              time: '05:30'
              weekday: [sun]
              month: [dec, jan, feb]
            - name: 'Estate'
              time: '05:30'
              weekday: [mon, wed, fri]              
              month: [jun, jul, aug]
            - name: 'Primavera e Autunno'
              time: '05:30'
              weekday: [mon, thu]
              month: [mar, apr, may, sep, oct, nov]    
          zones:
            - zone_id: 1
              duration: '00:05'
            - zone_id: 2
              duration: '00:05'
    - name: "Giardino Dietro Casa"
      enabled: true
      zones:
        - name: "Zona Muro"
          entity_id: 
            - switch.sonoff_10002e07a0
            - switch.sonoff_10007b5d9c_1
        - name: "Zona Melo"
          entity_id: 
            - switch.sonoff_10002e07a0
            - switch.sonoff_10007b5d9c_3
        - name: "Zona Scale"
          entity_id: 
            - switch.sonoff_10002e07a0
            - switch.sonoff_10007b5d9c_2
      sequences:
        - delay: "00:01"
          name: "Stagioni"
          schedules:
           # - name: "Sunrise"
           #   time:
           #    sun: "sunrise"
            - name: "Winter"
              time: "05:30"
              weekday: [sun]
              month: [dec, jan, feb]
            - name: "Summer"
              time: "05:30"
              weekday: [mon, wed, fri]
              month: [jun, jul, aug]
              duration: "00:15"
            - name: "Spring and Autumn"
              time: "05:30"
              weekday: [mon, thu]
              month: [mar, apr, may, sep, oct, nov]    
          zones:
            - zone_id: 1
              duration: '00:05'
            - zone_id: 2
              duration: '00:05'
            - zone_id: 3
              duration: '00:03'
#### IRRIGAZIONE - FINE####
```
![irri1](https://user-images.githubusercontent.com/76561249/156567620-e34540aa-2d14-4e63-9acd-36cd72b751ad.PNG)
![irri2](https://user-images.githubusercontent.com/76561249/156567644-9f67cb3a-8c85-4d1e-80d2-21039a1bad8a.PNG)

any suggestions?

**Comment by rgc99** [comment]
![Untitled 2](https://user-images.githubusercontent.com/13636007/156653488-056ed166-fa79-401f-a900-0e536c8e5c4a.png)
Change this to AM. You have run it for 12 hours and 10 minutes. It is a bit of a trap when using the time of day control to enter in a period. Better if you use this card for manual runs, you will need to install [time-picker-card](https://github.com/GeorgeSG/lovelace-time-picker-card).

```yaml
type: entities
title: Manual Run
entities:
  - entity: input_select.irrigation_unlimited_entities
    name: Controller/Zone
  - entity: input_select.irrigation_unlimited_sequences
    name: Controller/Sequence
  - type: custom:time-picker-card
    entity: input_datetime.irrigation_unlimited_run_time
    hour_mode: 24
    hour_step: 1
    minute_step: 1
    second_step: 5
    name: ''
    layout:
      embedded: true
    link_values: false
    hide:
      seconds: true
  - type: divider
  - type: custom:paper-buttons-row
    buttons:
      - name: Go
        tap_action:
          action: call-service
          service: irrigation_unlimited.shim_manual_run
          service_data:
            time_entity: input_datetime.irrigation_unlimited_run_time
            controller_zone_entity: input_select.irrigation_unlimited_entities
            controller_sequence_entity: input_select.irrigation_unlimited_sequences
      - name: Cancel
        tap_action:
          action: call-service
          service: irrigation_unlimited.shim_cancel
          service_data:
            controller_zone_entity: input_select.irrigation_unlimited_entities
```
