### ISSUE TITLE
Support for Long Term Statistics?

### ISSUE THREAD

**Issue by rmeekers** [rgc99/irrigation_unlimited#52]
**Is your feature request related to a problem? Please describe.**
I'd like to display the watering time per day. The mini graph card isn't sufficient and doesn't display all data correctly when using multiple zones at once.

**Describe the solution you'd like**
Support for https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by rgc99** [comment]
You can setup a long-term statistics sensor like this:
```yaml
template:
  - sensor:
    - name: Today Total C1 Z1
      state_class: total_increasing
      icon: mdi:sprinkler
      unit_of_measurement: s
      state: >
        {{ state_attr('binary_sensor.irrigation_unlimited_c1_z1', 'today_total') | float(0) }}
```
