### ISSUE TITLE
Enabling and disabling takes ~10 seconds

### ISSUE THREAD

**Issue by klassm** [rgc99/irrigation_unlimited#55]
Hi there,

first of all thanks for that great integration. I am starting to play around with the integration a bit - what I found is that the `irrigation_unlimited.shim_disable` and `irrigation_unlimited.shim_enable` methods take ~10 seconds to do something - no feedback whatsoever in between. Is there a reason why it is like that?

The debug logs don't really contain anything when doing the service call:

```
2022-04-16 10:23:11 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2022-04-16 10:23:00] service: disable, controller: 1, zone: 1, data: {"entity_id": ["binary_sensor.irrigation_unlimited_c1_z1"]}
```

The only thing that is mildly confusing is the following - but this line happens already before I trigger the service:
```
2022-04-16 10:22:28 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report issue to the custom component author for irrigation_unlimited using this method at custom_components/irrigation_unlimited/history.py, line 142: data = history.get_significant_states(
```

I mean this is not the most severe issue - it is just a weird UX when you click something and nothing happens.

## Version of the custom_component

2022.3.0 (via HACS)

## Configuration

There's nothing really special here - just something to start with:
```yaml
controllers:
  zones:
    - name: "Blumenbeet"
      entity_id: "switch.garten_bewaesserung_blumenbeete_safe"
      zone_id: "zone_blumenbeet"
    - name: "Rasen"
      entity_id: "switch.garten_bewaesserung_rasen_safe"
      zone_id: "zone_rasen"
    - name: "Topfplanzen"
      entity_id: "switch.garten_bewaesserung_topfplanzen_safe"
      zone_id: "zone_topfpflanzen"
    - name: "Zaun"
      entity_id: "switch.garten_bewaesserung_zaun_safe"
      zone_id: "zone_zaun"
  sequences:
    - delay: "00:01"
      repeat: 2
      schedules:
        - time: "21:00"
          month: [may, jun, jul, aug, sep]
      zones:
        - zone_id: "zone_zaun"
          duration: "00:02"
        - zone_id: "zone_blumenbeet"
          duration: "00:05"
        - zone_id: "zone_topfpflanzen"
          duration: "00:02"
        - zone_id: "zone_rasen"
          duration: "00:10"
```

Thank you so much and enjoy your easter holidays :-)
Matthias
