### ISSUE TITLE
Average sensor problem in automation

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation_unlimited#62]
Hello,

I use the automation you provide in [https://github.com/rgc99/irrigation_unlimited/blob/master/packages/irrigation_unlimited_adjustment.yaml](https://github.com/rgc99/irrigation_unlimited/blob/master/packages/irrigation_unlimited_adjustment.yaml).

The problem is that in Home Assistant core-2022.5 the average sensor has stopped working and the porject seems to be discontinued: [https://github.com/Limych/ha-average/issues/129](https://github.com/Limych/ha-average/issues/129).

I've looked at min-max and statistics sensors but I cannot find the start/end functionability of the average sensor.

Do you know if there is any option to continue with this cool automation?

Thanks.

**Comment by miguelpucela** [comment]
I've solved the problem with next code in case you can use it in the addon:

```
input_number:
  irrigation_unlimited_rain_1:
    name: "Irrigation Unlimited Rain -1"
    icon: mdi:weather-rainy
    initial: 0
    min: 0
    max: 200
    step: 0.1
  irrigation_unlimited_rain_2:
    name: "Irrigation Unlimited Rain -2"
    icon: mdi:weather-rainy
    initial: 0
    min: 0
    max: 200
    step: 0.1
  irrigation_unlimited_rain_3:
    name: "Irrigation Unlimited Rain -3"
    icon: mdi:weather-rainy
    initial: 0
    min: 0
    max: 200
    step: 0.1
  irrigation_unlimited_rain_4:
    name: "Irrigation Unlimited Rain -4"
    icon: mdi:weather-rainy
    initial: 0
    min: 0
    max: 200
    step: 0.1

sensor:
  - platform: template
    sensors:
      # Five day weighted rain total sensor. Fresno
      # Adjust the weight values (0.7, 0.3, 0.15, 0.05) to suit your needs (0.0 = ignore that day).
      irrigation_unlimited_rain_weighted_total:
        friendly_name: "Irrigation Unlimited Rain Weighted Total"
        unit_of_measurement: 'mm'
        icon_template: 'mdi:umbrella'
        value_template: >
          {% set rain_total = states('sensor.pws_precip_total') | float(default=0) %}
          {% set rain_total = rain_total + states('input_number.irrigation_unlimited_rain_1') | float(default=0) * 0.7 %}
          {% set rain_total = rain_total + states('input_number.irrigation_unlimited_rain_2') | float(default=0) * 0.3 %}
          {% set rain_total = rain_total + states('input_number.irrigation_unlimited_rain_3') | float(default=0) * 0.15 %}
          {% set rain_total = rain_total + states('input_number.irrigation_unlimited_rain_4') | float(default=0) * 0.05 %}
          {{ rain_total | round(1) }}

  - platform: statistics
    name: "Irrigation Unlimited Temperature 5 day moving average"
    entity_id: sensor.pws_temp
    state_characteristic: average_linear
    max_age:
      days: 5
    sampling_size: 300

automation:
  - id: irrigation_unlimited_update_rain_previous_days
    alias: "Irrigation Unlimited Update rain previous days"
    description: "Updates rain in Fresno for the 4 prevous days at midnight. For Irrigation Unlimited"
    trigger:
      # run at almost midnight
      - platform: time
        at: '23:59:00'
    condition: []
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.irrigation_unlimited_rain_4
        data:
          value: >-
            {{ states('input_number.irrigation_unlimited_rain_3') }} 
      - service: input_number.set_value
        target:
          entity_id: input_number.irrigation_unlimited_rain_3
        data:
          value: >-
            {{ states('input_number.irrigation_unlimited_rain_2') }} 
      - service: input_number.set_value
        target:
          entity_id: input_number.irrigation_unlimited_rain_2
        data:
          value: >-
            {{ states('input_number.irrigation_unlimited_rain_1') }} 
      - service: input_number.set_value
        target:
          entity_id: input_number.irrigation_unlimited_rain_1
        data:
          value: >-
            {{ states('sensor.pws_precip_total') }} 
    mode: single
```
