### ISSUE TITLE
How is the testing section supposed to work ?

### ISSUE THREAD

**Issue by alelucc** [rgc99/irrigation_unlimited#69]
Hi,
I was setting up this wonderful integration but i am struggling to understand how the testing section works because in the logs i can only find this: 
`2022-05-12 11:35:56 DEBUG (MainThread) [custom_components.irrigation_unlimited] INITIALISED`
`2022-05-12 11:35:56 INFO (MainThread) [custom_components.irrigation_unlimited] TEST_START [2023-01-04 05:00:00] test: 1, start: 2023-01-04 05:00:00, end: 2023-01-11 07:30:00`

My conf file is like this: 

```
testing:
  enabled: true
  speed: 60.0
  show_log: true
  output_events: true
  times:
    - name: "Test 1"
      start: "2023-01-04 05:00"
      end: "2023-01-11 07:30"
    - name: "Test 2"
      start: "2023-01-01 05:00"
      end: "2023-01-01 05:30"
controllers:
  zones:
    schedules:
      - time: "06:00"
        duration: "00:20"
```
I already checked in the logs that history and recorder are ok indeed i find this:
`2022-05-12 11:34:50 DEBUG (MainThread) [custom_components.irrigation_unlimited] START`
`2022-05-12 11:34:50 INFO (MainThread) [homeassistant.setup] Setup of domain irrigation_unlimited took 0.8 seconds`
