### ISSUE TITLE
Delay setting does not work in my case (valves just close/open immediately)

### ISSUE THREAD

**Issue by Notrial** [rgc99/irrigation_unlimited#70]
## Version of the custom_component

Latest,

## Configuration

```
    sequences:
      - name: "Spring"
        delay: "00:00:15"

Add your logs here.

```

## Describe the bug
Either this setting is not working as expected or I'm doing it wrong :)
I have a 15 sec delay between closing/opening the zones, but no matter what delay I enter zones just start one after each other without any noticeable delay.

## Debug log

```text

Add your logs here.

```

**Comment by rgc99** [comment]
Change the `granularity` setting. It is the internal clock and forms the base time units. By default it is 1 minute and all times will be rounded to increments of 60 seconds. Choose a value that is the smallest time you require.

```yaml
irrigation_unlimited:
  granularity: 15
  controllers:
    zones:
      - name: "Prema cesti"
        entity_id: "switch.sprinklers_1"
        show:
          timeline: true
      - name: "Prema susjedu"
        entity_id: "switch.sprinklers_3"
        show:
          timeline: true
      - name: "Jug dolje"
        entity_id: "switch.sprinklers_2"
        show:
          timeline: true
      - name: "Ispred terase"
        entity_id: "switch.sprinklers_4"
        show:
          timeline: true
      - name: "Kontra terase"
        entity_id: "switch.sprinklers_5"
        show:
          timeline: true
      - name: "Trampolin"
        entity_id: "switch.sprinklers_6"
        show:
          timeline: true
      - name: "Uz garažu"
        entity_id: "switch.sprinklers_7"
        show:
          timeline: true
      - name: "Kontra garaže"
        entity_id: "switch.sprinklers_8"
        show:
          timeline: true
    all_zones_config: 
      show: 
        timeline: true
    sequences:
      - name: "All"
        delay: "00:00:15"
        schedules:
          - name: "Spring"
            time: "21:00"
        zones:
          - zone_id: 1
            duration: "00:12"
          - zone_id: 2
            duration: "00:20"
          - zone_id: 3
            duration: "00:20"
          - zone_id: 4
            duration: "00:10"
          - zone_id: 5
            duration: "00:10"
          - zone_id: 6
            duration: "00:5"
          - zone_id: 7
            duration: "00:3"
          - zone_id: 8
            duration: "00:3"
```
