### ISSUE TITLE
No further adjustments after adjustment is giving 00:00:00

### ISSUE THREAD

**Issue by strehlma** [rgc99/irrigation_unlimited#72]
## Configuration

```yaml
irrigation_unlimited:
  controllers:
    zones:
      - name: "Garten vorne"
        entity_id: "switch.sprinkler_1"
        show:
          timeline: true
      - name: "Garten mitte"
        entity_id: "switch.sprinkler_3"
        show:
          timeline: true
      - name: "Garten hinten"
        entity_id: "switch.sprinkler_2"
        show:
          timeline: true
    sequences:
      - name: Garten
        delay: "00:01"
        schedules:
          - name: "Abends"
            time: "19:00"
        zones:
          - zone_id: 3
            duration: "00:40"
          - zone_id: 2
            duration: "00:15"
          - zone_id: 1
            duration: "00:15"
  - alias: "Irrigation adjustment - vorne"
    id: "irrigation_adjustment_garten_vorne"
    description: Adjust watering times based on smart irrigation calculations
    trigger:
      - platform: time
        at: "23:30"
    action:
      - service: irrigation_unlimited.adjust_time
        data:
          entity_id: binary_sensor.irrigation_unlimited_c1_z1
          actual: >
            {% set t = states('sensor.smart_irrigation_vorne_daily_adjusted_run_time') | int(-1) %}
            {% if t != -1 %}
              {{ '{:02d}:{:02d}:{:02d}'.format((t // 3600) % 24, (t % 3600) // 60, (t % 3600) % 60) }}
            {% else %}
              {{ "00:00:00" }}
            {% endif %}
    mode: single

  - alias: "Irrigation adjustment - mitte"
    id: "irrigation_adjustment_garten_mitte"
    description: Adjust watering times based on smart irrigation calculations
    trigger:
      - platform: time
        at: "23:30"
    action:
      - service: irrigation_unlimited.adjust_time
        data:
          entity_id: binary_sensor.irrigation_unlimited_c1_z2
          actual: >
            {% set t = states('sensor.smart_irrigation_mitte_daily_adjusted_run_time') | int(-1) %}
            {% if t != -1 %}
              {{ '{:02d}:{:02d}:{:02d}'.format((t // 3600) % 24, (t % 3600) // 60, (t % 3600) % 60) }}
            {% else %}
              {{ "00:00:00" }}
            {% endif %}
    mode: single

  - alias: "Irrigation adjustment - hinten"
    id: "irrigation_adjustment_garten_hinten"
    description: Adjust watering times based on smart irrigation calculations
    trigger:
      - platform: time
        at: "23:30"
    action:
      - service: irrigation_unlimited.adjust_time
        data:
          entity_id: binary_sensor.irrigation_unlimited_c1_z3
          actual: >
            {% set t = states('sensor.smart_irrigation_hinten_daily_adjusted_run_time') | int(-1) %}
            {% if t != -1 %}
              {{ '{:02d}:{:02d}:{:02d}'.format((t // 3600) % 24, (t % 3600) // 60, (t % 3600) % 60) }}
            {% else %}
              {{ "00:00:00" }}
            {% endif %}
    mode: single

  - alias: "Smart Irrigation reset bucket"
    id: "smart_irrigation_reset_bucket"
    description: Resets the Smart Irrigation bucket after watering
    trigger:
      - platform: state
        entity_id:
          # Add Irrigation Unlimited sensors here
          - binary_sensor.irrigation_unlimited_c1_m
        from: "on"
        to: "off"
    action:
      - service: smart_irrigation.smart_irrigation_vorne_reset_bucket
      - service: smart_irrigation.smart_irrigation_mitte_reset_bucket
      - service: smart_irrigation.smart_irrigation_hinten_reset_bucket

Add your logs here.

```

## Describe the bug
It seems, that there are no new adjustments to the duration after the adjustment was set to 00:00:00 once. 
The reset bucket automation isn't triggered any more. 
Probably because the controller is no set to 'on' and back to 'off' which should trigger the automation. Is this normal, that the controller isn't starting when the duration is set to 00:00:00?

## Debug log

```text

Add your logs here.

```
