### ISSUE TITLE
Allow negative pre/postamble

### ISSUE THREAD

**Issue by clau-bucur** [rgc99/irrigation_unlimited#73]
**Describe the solution you'd like**
Allow negative values for controller preable and postamble times.

**Additional context**
I could use this feature with my setup: I have a water pump controlled by a HA switch, which I would like to start **after irrigation zones are open**, and, most importantly, **stop before the irrigation zones are closed** as to prevent water hammers.

**Comment by rgc99** [comment]
This might be as simple as altering the schema. Bigger question is how should sequences operate. Do you have a delay between zones and should the pump run down and back up again when they change? I guess if you don't then there is a hard shut off and hammering.

**Comment by clau-bucur** [comment]
I'm not using any delay, and I'm really new to using your component so I'm sure I don't completely grasp it's operation mode.

My use case is pretty simple right now:
- I have two zones (grass and plants) which should run at the same time. Maybe, in the future (not sure yet) the plants zone will run longer than the grass zone
- I start irrigation 20 minutes past sunrise
- In the spring it will run once a week for 30 minutes. In the summer twice a week for 30 minutes (this is a work in progress, will have to calculate the optimal durations. hoping to use it together with HAsmartirrigation but I'm having troubles getting evapotranspiration values for my region)
- I want to allow water to soak, so I want to run:
       - 5 minutes
       - wait 5 minutes
       - run for the rest of 25 minutes

My YAML looks like this right now:
```
irrigation_unlimited:
  controllers:
    name: GME
    enabled: false
    # entity_id: switch.tank
    # preamble: '-00:01'
    # postamble: '-00:01'
    all_zones_config:
      show:
        timeline: true
    zones:
      - entity_id: switch.irrigation_mastered_zone_grass
        name: Grass
        show:
          timeline: true
      - entity_id: switch.irrigation_mastered_zone_plants
        name: Plants
        show:
          timeline: true
    sequences:
      - name: Spring and Autumn
        schedules:
          - name: After sunrise run 5 min
            time:
              sun: sunrise
              after: 00:20
            weekday: [sat]
            month: [apr, may, sep, oct]
            duration: 00:05

          #wait 5 min, then start again

          - name: After sunrise run 25 min
            time:
              sun: sunrise
              after: 00:30
            weekday: [sat]
            month: [apr, may, sep, oct]
            duration: 00:25
        zones:
          zone_id: [1, 2]

      - name: Summer
        schedules:
          - name: After sunrise run 5 min
            time:
              sun: sunrise
              after: 00:20
            weekday: [tue, sat]
            month: [jun, jul, aug]
            duration: 00:05

          #wait 5 min, then start again

          - name: After sunrise run 25 min
            time:
              sun: sunrise
              after: 00:30
            weekday: [tue, sat]
            month: [jun, jul, aug]
            duration: 00:25
        zones:
          zone_id: [1, 2]
```
In order to achieve my goal and to prevent water hammer I've created template switches which use scripts that would turn on and off with a delay the pump:
```
script:
  irrigation_zone_turn_on_grass:
    sequence:
      - service: switch.turn_on
        entity_id: switch.irrigation_zone_grass
      - delay: 2
      - service: switch.turn_on
        entity_id: switch.tank

  irrigation_zone_turn_on_plants:
    sequence:
      - service: switch.turn_on
        entity_id: switch.irrigation_zone_plants
      - delay: 2
      - service: switch.turn_on
        entity_id: switch.tank

  irrigation_zone_turn_off_grass:
    sequence:
      - if: "{{ not is_state('switch.irrigation_zone_plants', 'on') }}"
        then:
          - service: switch.turn_off
            entity_id: switch.tank
          - delay: 5 #prevent water hammer
      - service: switch.turn_off
        entity_id: switch.irrigation_zone_grass

  irrigation_zone_turn_off_plants:
    sequence:
      - if: "{{ not is_state('switch.irrigation_zone_grass', 'on') }}"
        then:
          - service: switch.turn_off
            entity_id: switch.tank
          - delay: 5 #prevent water hammer
      - service: switch.turn_off
        entity_id: switch.irrigation_zone_plants

switch:
  - platform: template
    switches:
      irrigation_mastered_zone_grass:
        value_template: "{{ is_state('switch.irrigation_zone_grass', 'on') }}"
        turn_on:
          service: script.irrigation_zone_turn_on_grass
        turn_off:
          service: script.irrigation_zone_turn_off_grass

      irrigation_mastered_zone_plants:
        value_template: "{{ is_state('switch.irrigation_zone_plants', 'on') }}"
        turn_on:
          service: script.irrigation_zone_turn_on_plants
        turn_off:
          service: script.irrigation_zone_turn_off_plants
```
However this is still work in progress and not sure if it completely works as expected, expecially if switches **irrigation_mastered_zone_grass** and **irrigation_mastered_zone_plants** are turned off at the same time. This will leave **switch.tank** turned on.
That's why I'd prefer to not have to do all these tricks but have your component handle it.

How I'd see it work:
- pump should be turned on with the preamble timeout (so after, if preamble is negative) ANY zone is turned on in a sequence.
- pump should be turned off with the postamble timeout (so before, if postamble is negative) THE LAST zone is turned off in a sequence.

**Comment by rgc99** [comment]
Further simplify the config. Good luck.

```yaml
irrigation_unlimited:
  controllers:
    name: GME
    enabled: true
    # entity_id: switch.tank
    preamble: '-00:01'
    postamble: '-00:01'
    all_zones_config:
      show:
        timeline: true
    zones:
      - name: Grass
        # entity_id: switch.irrigation_mastered_zone_grass
        show:
          timeline: true
      - name: Plants
        # entity_id: switch.irrigation_mastered_zone_plants
        show:
          timeline: true
    sequences:
      - name: After sunrise
        schedules:
          - name: Spring and Autumn
            time:
              sun: sunrise
              after: 00:20
            weekday: [sat]
            month: [apr, may, sep, oct]
          - name: Summer
            time:
              sun: sunrise
              after: 00:20
            weekday: [tue, sat]
            month: [jun, jul, aug]
        zones:
          - zone_id: [1, 2]
            duration: 00:05
            delay: 00:05
          - zone_id: [1, 2]
            duration: 00:25
```
