### ISSUE TITLE
Eco-mode for manual run

### ISSUE THREAD

**Issue by clau-bucur** [rgc99/irrigation_unlimited#76]
**Describe the solution you'd like**
Is it possible to have the manual mode run in eco mode or follow the set schedule pattern ?
For example, if you have your sequence schedule
 - run 5 minutes
 - stop 5 minutes
 - then run for 15 minutes.
If you specify start manual with a runtime of 20 minutes, it should follow the same pattern.

**Describe alternatives you've considered**
Create a script which will start with a small runtime, delay for the same amount, then run again with the second amount.

**Comment by rgc99** [comment]
Create a sequence for example.
```yaml
irrigation_unlimited:
  controllers:
    zones:
      - entity_id: "switch.my_switch_1"
    sequences:
      - name: Eco
        schedules:
          - time: "05:00"
        zones:
          - zone_id: 1
            duration: "00:05"
            delay: "00:05"
          - zone_id: 1
            duration: "00:15"
```
Now you can run this by specifying `sequence_id: 1` in the manual run. If this is to be _only_ for manual run then set the schedule date to the 31st February. As you want to run a sequence make sure the entity_id is the controller. More details can be found in the documentation.
