### ISSUE TITLE
Events not triggered for manual runs

### ISSUE THREAD

**Issue by clau-bucur** [rgc99/irrigation_unlimited#77]
**Describe the bug**
I do not receive events (irrigation_unlimited_start, irrigation_unlimited_finish) for manual run sessions.

**Expected behavior**
Events should be also sent in case of manual runs, with a way to differentiate between scheduled and manual sessions.

**Comment by rgc99** [comment]
You will receive these events at the start and end of a _sequence_, not an individual zone. A manual run can be distinguished by the `schedule.index` being empty/blank.

**Comment by f616** [comment]
I do not know how to listen to the irrigation_unlimited_finish. Could some one point me to the right direction?
I've tried to implement the irrigation_unlimited_finish example, but without any success (there seems there is nothing triggered).
I've also tryed to listen to the 'irrigation_unlimited_finish' event in the HA Developer Tools\Events\Listen to events without any sucess either.

![image](https://user-images.githubusercontent.com/3826426/184544558-7ad9c997-0afe-42bb-88bd-02cc5613c713.png)

**Comment by rgc99** [comment]
You only receive events for the start and end of a _sequence_. The beginning and finish of a zone do not produce these events but can be tracked using the state platform as the trigger. For example:

```yaml
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.irrigation_unlimited_c1_z1
        from: "off"
        to: "on"
```
