### ISSUE TITLE
Event/notification when entire controller finishes

### ISSUE THREAD

**Issue by hvorragend** [rgc99/irrigation_unlimited#78]
**Is your feature request related to a problem? Please describe.**
Since yesterday I am using your example (https://github.com/rgc99/irrigation_unlimited#irrigation_unlimited_start-irrigation_unlimited_finish) to send me a notification (based on the 'irrigation_unlimited_finish'-event) if the irrigation is finished. Now I realized the this events fires if a sequence is finished and not the entire controller.

Is it possible to fire an event? Or should I just use the state change of 'binary_sensor.irrigation_unlimited_c1_m'?

By the way: I'm a little confused as I don't understand why I was receiving the notifications at these times.

**Repeat 1**
Zone 1+2:  06:30 on | 06:40 off
Zone 3: 06:41 on | 06:46 off
Zone 4: 06:47 on | 06:52 off

**Repeat 2**
Zone 1+2:  06:53 on | 07:03 off
Zone 3: 07:04 on | 07:09 off
Zone 4: 07:10 on | 07:15 off

**Events fired at:**
- 06:48
- 06:51
- 07:17

I see no pattern.

My configuration:

```
irrigation_unlimited:
  controllers:
    entity_id: switch.gartenpumpe_timer
    name: Gartenbewaesserung
    enabled: true
    preamble: "00:01"
    postamble: "00:01"
    zones:
      - name: "Terrasse"
        entity_id: "switch.versenkregner_terrasse_timer"
        enabled: true
        maximum: "00:45"
      - name: "Hinten"
        entity_id: "switch.versenkregner_hinten_timer"
        enabled: true
        maximum: "00:45"
      - name: "Seite"
        entity_id: "switch.versenkregner_seite_timer"
        enabled: true
        maximum: "00:30"
      - name: "Vorne"
        entity_id: "switch.versenkregner_vorne_timer"
        enabled: true
        maximum: "00:30"
    sequences:
      - name: "Gesamt"
        delay: "00:01"
        repeat: 2
        schedules:
          - time: "06:30"
            # day: "odd"
            month: [may, jun, jul, aug, sep]
        zones:
          - zone_id: [1, 2]
            duration: "00:10"
          - zone_id: 3
            duration: "00:05"
          - zone_id: 4
            duration: "00:05"
```

**Describe the solution you'd like**
Timely events for sequences and controllers.
