### ISSUE TITLE
Manual run of sequence just starts controller not the zones

### ISSUE THREAD

**Issue by hvorragend** [rgc99/irrigation_unlimited#79]
**Describe the bug**

I am using your manual run card. It is possible to run a single zone. But If I try to start the sequence (here: your "multi zones" = my "gesamt") as shown in the following screenshot...

![image](https://user-images.githubusercontent.com/343705/174433841-5c00bd99-a746-411e-9659-09d405cf7d85.png)

... only the controller was started. My "master valve" (here: entity_id: switch.gartenpumpe_timer) was powered on and then nothing more happens

![image](https://user-images.githubusercontent.com/343705/174433856-b1f8e0bb-33c9-410e-a02d-662e9a47078a.png)

**Expected behavior**
I thought that all single zones are started as configured.

Same on smartphone and desktop-computer.

**Config:**
```
irrigation_unlimited:
  controllers:
    entity_id: switch.gartenpumpe_timer
    name: Gartenbewaesserung
    enabled: true
    preamble: "00:01"
    postamble: "00:01"
    zones:
      - name: "Terrasse"
        entity_id: "switch.versenkregner_terrasse_timer"
        enabled: true
        maximum: "00:45"
      - name: "Hinten"
        entity_id: "switch.versenkregner_hinten_timer"
        enabled: true
        maximum: "00:45"
      - name: "Seite"
        entity_id: "switch.versenkregner_seite_timer"
        enabled: true
        maximum: "00:30"
      - name: "Vorne"
        entity_id: "switch.versenkregner_vorne_timer"
        enabled: true
        maximum: "00:30"
    sequences:
      - name: "Gesamt"
        delay: "00:01"
        repeat: 2
        schedules:
          - time: "06:30"
            # day: "odd"
            month: [may, jun, jul, aug, sep]
        zones:
          - zone_id: [1, 2]
            duration: "00:10"
          - zone_id: 3
            duration: "00:05"
          - zone_id: 4
            duration: "00:05"

```
