### ISSUE TITLE
Watering starting at sunset and lasting until dawn

### ISSUE THREAD

**Issue by Dinth** [rgc99/irrigation_unlimited#80]
**Is your feature request related to a problem? Please describe.**
Hi. I have read the documentation, but it seems that while im able to start the watering at sunset, i cannot schedule it to finish at dawn at same time. What i need to do is to enable constant watering overnight. 

**Describe the solution you'd like**
An simple way to schedule watering overnight - from sunset to sunrise.

**Describe alternatives you've considered**
Currently im using a HA automations to enable and disable watering at sunset and surise, but since i started migrating whole my watering system to irrigation_unlimited, i would also like to migrate that automation too.

**Comment by rgc99** [comment]
A fun problem. You can schedule to start or finish at sunrise or sunset but not both, however, here's how you can do it.

This is an automation that will run 1 hour before sunset. It uses the [sun integration](https://www.home-assistant.io/integrations/sun/) to calculate the duration from sunset to sunrise and then set this via the `adjust_time` service call.

You should create a schedule that starts at sunset and just put in a nominal duration. The duration will be replaced by the service call. Please take note of the comments in the automation as you must change it to suit your configuration.

Let me know how you get on as I would like to add this to the cookbook of interesting things you can do.

```yaml
automation:
  - id: 'IU1655789912900'
    alias: IU Overnight
    description: Run irrigation from sunset to sunrise
    trigger:
      - platform: sun
        event: sunset
        offset: -00:60:00
    condition: []
    action:
      service: irrigation_unlimited.adjust_time
      data:
        # -------------------------------------------------------------------
        # Please see documentation regarding the adjust_time service call.
        # Choose an option below. Comment out/delete/change as needed.
        # *** This will NOT work as is. ***
        # 1. Adjust a single zone. Change the zone as required
        # entity_id: binary_sensor.irrigation_unlimited_c1_z1
        # 2. Adjust a sequence. Change the sequence_id as required
        # entity_id: binary_sensor.irrigation_unlimited_c1_m
        # sequence_id: 1
        # -------------------------------------------------------------------
        actual: >
          {% set t1 = as_datetime(state_attr("sun.sun", "next_setting")).replace(microsecond=0) %}
          {% set t2 = as_datetime(state_attr("sun.sun", "next_rising")).replace(microsecond=0) %}
          {{ t2 - t1 }}
    mode: single
```
