### ISSUE TITLE
Check if an irrigation valve state has changed

### ISSUE THREAD

**Issue by Dinth** [rgc99/irrigation_unlimited#81]
**Is your feature request related to a problem? Please describe.**
As my irrigation Zigbee valves are located outside, the connection is not very strong and changing their state in HA does not always take an effect and needs to be repeated. 
**Describe the solution you'd like**
It would be nice if this integration would perform a check about 5s after turning the valve switch on and off, to check if the switches state has actually changed and if not - try turning the valve on or off again.

**Comment by rgc99** [comment]
This functionality is now available in the latest release. Details can be found in the readme under Check Back.

**Comment by Dinth** [comment]
Thanks @rgc99. Would you mind providing some configuration example in the doc?

**Comment by rgc99** [comment]
The functionality is enabled by default with a 30 second delay and 3 retries. I will include this in the readme.
```yaml
irrigation_unlimited:
  controllers:
      zones:
        - name: "Zone 1"
          entity_id: switch.my_switch
          check_back:
            delay: 20
            retries: 4
```
Any errors are logged. An event is also fired which is useful to send a notification. An email example can be found in the readme.
