### ISSUE TITLE
Cannot start a manual sequence if disabled

### ISSUE THREAD

**Issue by alelucc** [rgc99/irrigation_unlimited#82]
Hi,
the integration works great, but i was wondering why a disabled sequence cannot be manually triggered.
In other words i want a specific sequence of zones never be triggered by a time schedule but only with the manual_run service call.

I want this because the "main" sequences are very complicated (different zones in different days combined with "eco" mode) and i want a simpler sequence that can be triggered at the need. But if i disable the sequence i cannot start in manual mode and if i keep enabled i cannot make it never run on schedule because of the required -time: setting.

How can this be achieved?

```
controllers:
  - name: "Controller"
    entity_id: switch.irrigazione_run
    zones:
      - entity_id: switch.irrigazione_1
      - entity_id: switch.irrigazione_2
      - entity_id: switch.irrigazione_3
      - entity_id: switch.irrigazione_4
      - entity_id: switch.irrigazione_5
      - entity_id: switch.irrigazione_6
      - entity_id: switch.irrigazione_7
      - entity_id: switch.irrigazione_8
    sequences:
      - name: "seq1"
        schedules:
          - time: "6:40"
            month: [mar, apr, may, jun, jul, aug]
        repeat: 2
        delay: "x"
        zones:
          - zone_id: 1
            duration: "x"
      - name: "seq2"
        schedules:
          - time: "x"
            day: even
            month: [mar, apr, may, jun, jul, aug]
        repeat: 2
        zones:
          - zone_id: 2
            duration: "x"
         ...
          - zone_id: 8
            duration: "x"
      - name: "MANUAL SEQUENCE"
        schedules:
          - time: "00:00"
        zones:
          - zone_id: 1
            duration: "x"
          - zone_id: 2
            duration: "x"
          - zone_id: 3
            duration: "x"
          - zone_id: 4
            duration: "x"
          - zone_id: 5
            duration: "x"
          - zone_id: 6
            duration: "x"
          - zone_id: 7
            duration: "x"

```
