### ISSUE TITLE
manual_run missing documentation

### ISSUE THREAD

**Issue by tunguskar** [rgc99/irrigation_unlimited#83]
Hi There,

I get a little bit stuck because I do not want to irrigate automated. What I have:

- 8 Sections (8 valves)

What I want is 
- manually start an irrigation cycle with this 8 valves.
- Each section shall have a activate/deactivate switch and a timer in minutes how long to irrigate. 
- I want to set the order of the irrigation
- I want to have just one valve open at a time with a little delay between switching

Is this possible with this module? The manual does not bring me forward with this situation. 

If this is possible, can you provide me a little example with maybe two valves?

Thanks in advance.

Kind Regards

Christian

**Comment by rgc99** [comment]
Hi Christian,

Yes, this module will do all of the above. Look at sequences which allow you to create a 'playlist' by defining the order, duration and delay for each valve. Here is a link to the documentation which show a three valve [sequence example](https://github.com/rgc99/irrigation_unlimited#sequence-example).

Regards

**Comment by tunguskar** [comment]
hm I had a look on this example, maybe I'm the noob too big. There is also a schedule tag with a time. This, in my case, hast to be undefined, or better I have to set it via a button "start irrigation"?

The one hand is the logic,

the other is the GUI,

In my configuration.yaml I would suggest this with undefined 

```yaml
irrigation_unlimited:
  controllers:
    enabled: true
    zones:
      - entity_id: "switch.my_switch_1"
         enabled: true
          - schedules:
              - time: ""
                duration: "00:10"
      - entity_id: "switch.my_switch_2"
         enabled: true
         - schedules:
              - time: ""
                duration: "00:10"
    sequences:
      - duration: "00:10"
        delay: "00:01"
        schedules:
          - time: ""
        zones:
          - zone_id: 1
          - zone_id: 2
```

**Comment by rgc99** [comment]
If you are trying to create a zone/sequence solely for the purpose of a manual run and _never_ want it automatically operate then here is a little trick.
```yaml
irrigation_unlimited:
  controllers:
    enabled: true
    zones:
      - entity_id: "switch.my_switch_1"
        enabled: true
        - schedules:
            - time: "05:00"
              month: [feb]
              day: [31]
              duration: "00:10"
      - entity_id: "switch.my_switch_2"
        enabled: true
        - schedules:
            - time: "05:00"
              month: [feb]
              day: [31]
              duration: "00:10"
    sequences:
      - duration: "00:10"
        delay: "00:01"
        schedules:
          - time: "05:00"
            month: [feb]
            day: [31]
        zones:
          - zone_id: 1
          - zone_id: 2
```
The secret is to add a month and day filter to the schedule(s). In this case it will only run on the 31st of February. The `time:` is irrelevant but just be something valid. I will add this to the documentation.
