### ISSUE TITLE
[Question] HAsmartirrigation Integration

### ISSUE THREAD

**Issue by Kurisutian** [rgc99/irrigation_unlimited#9]
Since it was mentioned in the description of the project, how exactly would an integration of HAsmartirrigation to distinguish dynamic watering duration look like? How would the result value of the HAsmartirrigation sensor have to be integrated into the yaml file exactly?
Thanks for creating this wonderful integration which really helps a lot.

**Comment by rgc99** [comment]
Glad this project is working out for you. Once you have things up and running there are a number of service calls available. One of these service calls allows you to adjust the watering times you have setup in the yaml file.
[HAsmartirrigation](https://github.com/jeroenterheerdt/HAsmartirrigation) provides a number of sensors with the hourly or daily adjusted run times. You need to create an automation that takes the data from the HAsmartirrigation sensor and makes a service call to `irrigation_unlimited.adjust_time`.
Personally I have not used this integration and instead use observation data provided by my personal weather station to adjust watering times based on rainfall and temperature. Details can be found in the documentation. There are many thoughts and ideas along with numerous weather services giving a lot of scope for creating adjustments.

**Comment by Kurisutian** [comment]
Thanks for getting back to me about this. I have no clue how to work with it, since all of my automation so far was done with Node-Red. Also I do not own a weather station since I have not found one yet, which suits my needs and is available on the German market (if you happen to know any, let me know as I would be glad to set something up on the roof). 
I think the beauty of the HAsmartirrigation is the fact that they calculate a value out of evaporation, area to cover and how much water the individual sprinklers need. So this is highly custom and even with my own weather station I would still love to have this data integrated. 
So could you provide an example how to work with HAsmartirrigation and how it would be set up to adjust time. I only started looking a bit more under the surface and I'm not that much of a programmer so I have my difficulties adjusting your examples to what I want to archive. Any hint or idea would be highly appreciated. 

Thank you very much! :smiley:

**Comment by rgc99** [comment]
Not sure they sell my model of weather station any more but this is very much like it. https://www.ebay.com.au/itm/262073907445. The main thing is it sends the information to [weather underground](https://www.wunderground.com) and there is a HA integration https://github.com/cytech/Home-Assistant-wundergroundpws that will pull the data back into HA.

This automation runs at 04:00 and takes the calculated run time from HAsmartirrigation and updates Irrigation Unlimited with the new watering time. It then calls HAsmartirrigation to reset the bucket.

Hopefully this will point you in the right direction.

```yaml
- alias: Smart Irrigation
  description: Adjust watering times
  trigger:
  - platform: time
    at: 04:00
  action:
  - service: irrigation_unlimited.adjust_time
    data:
      entity_id: binary_sensor.irrigation_unlimited_c1_z1
      actual: >
        {% set t = states('sensor.smart_irrigation_daily_adjusted_run_time') | int %}
        {{ '{:02d}:{:02d}:{:02d}'.format((t // 3600) % 24, (t % 3600) // 60, (t % 3600) % 60) }}
  - service: smart_irrigation.smart_irrigation_reset_bucket
  mode: single
```
