### ISSUE TITLE
show example in README.md

### ISSUE THREAD

**Issue by miguelpucela** [rgc99/irrigation_unlimited#90]
I don't know if I'm right or I have missed something, buy maybe next code is not correct:

```
irrigation_unlimited:
  controllers:
    zones:
      all_zones_config: # <= Add these three lines <─┐
        show: # <= to the configuration            <─┤
          timeline: true # <= for all zones        <─┘
      entity_id: "switch.my_switch"
      show: # <= Add these two lines to the                    <─┐
        timeline: true # <= configuration for individual zones <─┘
      schedules:
        - time: "06:00"
          duration: "00:20"
```

I think according to REAMDE.md parameters, as `all_zones_config` is a parameter of `controller` objects, it should be:

```
irrigation_unlimited:
  controllers:
    all_zones_config: # <= Add these three lines <─┐
      show: # <= to the configuration            <─┤
        timeline: true # <= for all zones        <─┘
    zones:
      entity_id: "switch.my_switch"
      show: # <= Add these two lines to the                    <─┐
        timeline: true # <= configuration for individual zones <─┘
      schedules:
        - time: "06:00"
          duration: "00:20"
```

Please, correct me if I'm wrong.
