### ISSUE TITLE
Sequence not working(?)

### ISSUE THREAD

**Issue by AlessandroTischer** [rgc99/irrigation_unlimited#91]
## Version of the custom_component
2022.08

## Configuration

```
irrigation_unlimited:
  controllers:
    - name: "Giardino"
      zones:
        - name: "Sud"
          entity_id: "switch.sprinkler_1"
        - name: "Ovest"
          entity_id: "switch.sprinkler_2"
        - name: "Nord"
          entity_id: "switch.sprinkler_3"
        - name: "Est"
          entity_id: "switch.sprinkler_4"
        - name: "Magnolia"
          entity_id: "switch.sprinkler_5"
        - name: "Aceri"
          entity_id: "switch.sprinkler_6"
      sequences:
          schedules:
            - time: "21:35"
#            - time:
#                sun: "sunset"
#                after: "00:39"
              anchor: start
          zones:
            - zone_id: 2
            - zone_id: 3
            - zone_id: 4
            - zone_id: 5
            - zone_id: 6
    - name: "Aiuole"
      zones:
        - name: "Aiuole"
          entity_id: "switch.sprinkler_7"
      sequences:
        - name: "Aiuole"
          schedules:
          - name: "Prima dell'alba"
            time:
              sun: 'sunrise'
              before: '00:20'
            duration: '00:07'
          - name: "Dopo il tramonto"
            time:
              sun: 'sunset'
              after: '00:30'
            duration: '00:07'
          zones:
            - zone_id: 1

```

## Describe the bug

I'm sure I got something wrong somewhere. It's my first time trying implementing irrigation unlimited.

I'm using SmartIrrigation to get irrigation timings for the controller named "Giardino". 
The controller "Aiuole" works fine.
The controller "Giardino" has a sequence which should run the sprinklers in order from 1 to 6. For some reason it works correctly only for the first in the sequence (this is why in my config you can see only 2 to 6: it's a test. Before it was 1 to 6). 
After the first one, the run times from SmartIrrigation are not used, nor the sprinklers switched on.

These are my automations:

```

alias: Smart Irrigation Adjustment
description: Adjust watering times based on smart irrigation calculations
trigger:
  - platform: time_pattern
    minutes: /58
condition: []
action:
  - service: irrigation_unlimited.adjust_time
    data:
      actual: >-
        {{
        timedelta(seconds=states('sensor.smart_irrigation_sud_hourly_adjusted_run_time')
        | int(0))}}
      entity_id: binary_sensor.irrigation_unlimited_c1_z1
    enabled: true
  - service: irrigation_unlimited.adjust_time
    data:
      actual: >-
        {{
        timedelta(seconds=states('sensor.smart_irrigation_ovest_hourly_adjusted_run_time')
        | int(0))}}
      entity_id: binary_sensor.irrigation_unlimited_c1_z2
    enabled: true
  - service: irrigation_unlimited.adjust_time
    data:
      actual: >-
        {{
        timedelta(seconds=states('sensor.smart_irrigation_nord_hourly_adjusted_run_time')
        | int(0))}}
      entity_id: binary_sensor.irrigation_unlimited_c1_z3
    enabled: true
  - service: irrigation_unlimited.adjust_time
    data:
      actual: >-
        {{
        timedelta(seconds=states('sensor.smart_irrigation_est_hourly_adjusted_run_time')
        | int(0))}}
      entity_id: binary_sensor.irrigation_unlimited_c1_z4
    enabled: true
  - service: irrigation_unlimited.adjust_time
    data:
      actual: >-
        {{
        timedelta(seconds=states('sensor.smart_irrigation_magnolia_hourly_adjusted_run_time')
        | int(0))}}
      entity_id: binary_sensor.irrigation_unlimited_c1_z5
    enabled: true
  - service: irrigation_unlimited.adjust_time
    data:
      actual: >-
        {{
        timedelta(seconds=states('sensor.smart_irrigation_aceri_hourly_adjusted_run_time')
        | int(0))}}
      entity_id: binary_sensor.irrigation_unlimited_c1_z6
    enabled: true
mode: single


```

```

alias: Smart Irrigation Reset Bucket
description: Resets the Smart Irrigation bucket after watering
trigger:
  - platform: state
    entity_id:
      - binary_sensor.irrigation_unlimited_c1_z1
    from: "on"
    to: "off"
    id: Sud
  - platform: state
    entity_id:
      - binary_sensor.irrigation_unlimited_c1_z2
    from: "on"
    to: "off"
    id: Ovest
  - platform: state
    entity_id:
      - binary_sensor.irrigation_unlimited_c1_z3
    from: "on"
    to: "off"
    id: Nord
  - platform: state
    entity_id:
      - binary_sensor.irrigation_unlimited_c1_z4
    from: "on"
    to: "off"
    id: Est
  - platform: state
    entity_id:
      - binary_sensor.irrigation_unlimited_c1_z5
    from: "on"
    to: "off"
    id: Magnolia
  - platform: state
    entity_id:
      - binary_sensor.irrigation_unlimited_c1_z6
    from: "on"
    to: "off"
    id: Aceri
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Sud
        sequence:
          - service: smart_irrigation.smart_irrigation_sud_reset_bucket
            data: {}
      - conditions:
          - condition: trigger
            id: Ovest
        sequence:
          - service: smart_irrigation.smart_irrigation_ovest_reset_bucket
            data: {}
      - conditions:
          - condition: trigger
            id: Sud
        sequence:
          - service: smart_irrigation.smart_irrigation_nord_reset_bucket
            data: {}
      - conditions:
          - condition: trigger
            id: Ovest
        sequence:
          - service: smart_irrigation.smart_irrigation_est_reset_bucket
            data: {}
      - conditions:
          - condition: trigger
            id: Sud
        sequence:
          - service: smart_irrigation.smart_irrigation_magnolia_reset_bucket
            data: {}
      - conditions:
          - condition: trigger
            id: Ovest
        sequence:
          - service: smart_irrigation.smart_irrigation_aceri_reset_bucket
            data: {}
    default: []


```

I post some pictures to make it a little more clear:

![image](https://user-images.githubusercontent.com/23379317/192046840-d42cebe5-120f-49c6-b33e-01f0973116e4.png)

Actual sprinklers entities:
![image](https://user-images.githubusercontent.com/23379317/192047077-811f0b70-c977-435f-b422-34b90b89d87a.png)

**Comment by rgc99** [comment]
Can you post the system log entries. You will first need to turn on debug messages by adding the following to your config.

```yaml
logger:
  default: info
  logs:
    custom_components.irrigation_unlimited: debug
``` 

In Settings -> System -> Log and search for 'irrigation_unlimited'. The messages I am particularly interested in should look like the following but post what is available:

2022-09-23 16:58:11.291 DEBUG (MainThread) [custom_components.irrigation_unlimited] CALL [2022-09-23 16:58:11] service: adjust_time, controller: 1, zone: 1, data: {"entity_id": "binary_sensor.irrigation_unlimited_c1_z1", "actual": "11:44:43"}
