### ISSUE TITLE
After reboot: preamble entity switch state not in sync with real state 

### ISSUE THREAD

**Issue by Kolia56** [rgc99/irrigation_unlimited#93]
## Version
v2022.11.0

## Configuration
```
controllers:
  name: "Controleur 1"
  all_zones_config:
    show:
      timeline: true
    allow_manual: true
  preamble: "00:01"
  postamble: "00:05"
  entity_id: switch.alimentation_electrovannes
  zones:
    - name: Café François
      entity_id: switch.vanne_atelier_gui
    - name: Maison journalier
      entity_id: switch.vanne_maison_journalier_gui
    - name: Pelouse
      entity_id : switch.vanne_jardin_devant_gui
  sequences:
    - name: nuit
      delay: "00:01"
      schedules:
        - time: "20:30"
      zones:
        - zone_id: 1
          duration: "00:30"
        - zone_id: 2
          duration: "00:20"
    - name: jour
      duration: "00:05"
      delay: "00:55"
      repeat: 7
      schedules: 
        - time: "12:00"
      zones:
        - zone_id: 2
    - name: Pelouse seule
      schedules:
        - time: 02:30
      zones:
        - zone_id: 3
          duration: "00:01"
          delay: "00:01"
        - zone_id: 3
          duration: "00:20"
```

## Describe the bug
I did not pay much attention until now, but since some time, each time HA is restarted the switch in the preamble section is set to On whereas it's physical state is Off. 

## Debug log
```
This error originated from a custom integration.

Logger: custom_components.irrigation_unlimited
Source: custom_components/irrigation_unlimited/irrigation_unlimited.py:4066
Integration: Irrigation Unlimited (documentation, issues)
First occurred: December 2, 2022 at 21:56:59 (1 occurrences)
Last logged: December 2, 2022 at 21:56:59

SYNCHRONISATION [2022-12-02 21:56:56] Switch does not match current state: switch: switch.alimentation_electrovannes

```

**Comment by rgc99** [comment]
During initialisation the switches are checked and synchronised. HA seems to think the switch is On so Irrigation Unlimited tries to turn it Off. At this time, I think the switch _should_ be off which is correct, or have I got this wrong.

You can prevent the syncronisation by adding the following to the config (it will still report the miss match).
```yaml
irrigation_unlimited:
  sync_switches: false
  ...
```
If you add the above, take a look in Developer Tools -> STATES and see what HA thinks the state of the switch.alimentation_electrovannes entity is.
