### ISSUE TITLE
sequences improvements - working one by one

### ISSUE THREAD

**Issue by pavel-dpa** [rgc99/irrigation_unlimited#99]
Thanks for this incredible implementation.
Previously using own written system on Smartthing with weather and other features integration.

And I have an question - do in possible with configuration below somehow run zone by zone with setuped repeating?
sequences:
        - delay: "00:01"
          schedules:
            time:
              sun: "sunrise"
              before: "00:10"
            anchor: finish
          zones:
              - zone_id: 1
                duration: "00:05"
                repeat: 2
              - zone_id: 2
                duration: "00:10"
                repeat: 3
			  - zone_id: 3
                duration: "00:15"
                repeat: 2

What I mean - by this config run   sequences in order : Zone 1 (5min) -> Zone 2 (10min) ->Zone 3 (15min)-> Zone 1 (5min) -> Zone 2 (10min) ->Zone 3 (15min)->Zone 2 (10min)

That give soil little bit better absorption in comparing when we just run zone1-zone1-zone1 with pauses as for me.

Is't possible somehow to configure ?

**Comment by pavel-dpa** [comment]
and one more thing - I do understand that I can manage this case by correct setup few schedulers for different counts of repeat and than manage that by schedulers offset depend on run time. 
But maybe that could be something which I missed.

**Comment by rgc99** [comment]
This comes close to what you want except Zone 2 is run 2 x 15min instead of 3 x 10min.
```yaml
sequences:
  - delay: "00:01"
    repeat: 2
    schedules:
      time:
        sun: "sunrise"
        before: "00:10"
      anchor: finish
    zones:
      - zone_id: 1
        duration: "00:05"
      - zone_id: 2
        duration: "00:15"
      - zone_id: 3
        duration: "00:15"
```
You can also include a zone more than once in a sequence for example
```yaml
    zones:
      - zone_id: 1
        duration: "00:05"
      - zone_id: 2
        duration: "00:10"
      - zone_id: 3
        duration: "00:15"
      - zone_id: 2
        duration: "00:10"
```

**Comment by rgc99** [comment]
To do exactly what you require this is what you will need to do.
```yaml
sequences:
  - delay: "00:01"
    schedules:
      time:
        sun: "sunrise"
        before: "00:10"
      anchor: finish
    zones:
      - zone_id: 1
        duration: "00:05"
      - zone_id: 2
        duration: "00:10"
      - zone_id: 3
        duration: "00:15"
      - zone_id: 1
        duration: "00:05"
      - zone_id: 2
        duration: "00:10"
      - zone_id: 3
        duration: "00:15"
      - zone_id: 2
        duration: "00:10"
```
